// @generated by scripts/gen_makernote_conv.pl from ExifTool 13.59. DO NOT EDIT.
//
// The ValueConv and PrintConv expressions on the MakerNote Main tables, carried
// over verbatim. `tags::conv_expr` evaluates them and declines anything outside
// its grammar, which leaves the raw value -- the same answer a reader that knew
// nothing of the conversion would give.

/// The RawConv expression ExifTool applies to a MakerNote Main tag.
#[must_use]
pub fn raw_conv_expr(maker: &str, tag: u16) -> Option<&'static str> {
    Some(match (maker, tag) {
        ("Canon", 0x0028) => "$val eq \"\\0\" x 16 ? undef : $val", // ImageUniqueID
        ("Canon", 0x0038) => "$val=~/^.{4}([^\\0]+)/s ? $1 : undef", // BatteryType
        ("FujiFilm", 0x100b) => "$val == 0x100 ? undef : $val", // NoiseReduction
        ("Minolta", 0x0081) => "$self->ValidateImage(ref $val ? $val : \\$val, $tag)", // PreviewImage
        ("Nikon", 0x0002) => "$val eq \"\\0\\0\\0\\0\" ? undef : $val", // ISO
        ("Nikon", 0x0007) => "$$self{FocusMode} = $val", // FocusMode
        ("Nikon", 0x0034) => "$$self{ShutterMode} = $val", // ShutterMode
        ("Nikon", 0x0044) => "($val) ? $val : undef", // JPGCompression
        ("Olympus", 0x0207) => "$self->{CameraType} = $val", // CameraType
        ("Olympus", 0x0280) => "$self->ValidateImage(ref $val ? $val : \\$val, $tag)", // PreviewImage
        ("Panasonic", 0x0086) => "$val==65535 ? undef : $val", // ManometerPressure
        ("Panasonic", 0x00c5) => "return undef unless $val; require Image::ExifTool::Olympus; # (to load Composite LensID) return $val;", // LensTypeModel
        ("Panasonic", 0x00d1) => "$val > 0xfffffff0 ? undef : $val", // ISO
        ("Panasonic", 0x00e4) => "return undef unless $val; require Image::ExifTool::Olympus; # (to load Composite LensID) return $val;", // LensTypeModel
        ("Pentax", 0x0005) => "$$self{PentaxModelID} = $val", // PentaxModelID
        ("Pentax", 0x0006) => "$$self{PentaxDate} = $val", // Date
        ("Pentax", 0x0007) => "$$self{PentaxTime} = $val", // Time
        ("Pentax", 0x0050) => "$val ? $val : undef", // ColorTemperature
        ("Pentax", 0x005d) => "length($val) == 4 ? unpack(\"N\",$val) : undef", // ShutterCount
        ("Pentax", 0x0076) => "$val =~ / (\\d+)/ and $$self{FacesDetected} = $1; $val", // FaceDetect
        ("Sanyo", 0x0100) => "$self->ValidateImage(\\$val,$tag)", // SanyoThumbnail
        ("Sony", 0x2001) => "return \\$val if $val =~ /^Binary/; $val = substr($val,0x20) if length($val) > 0x20; # return \\$val if $val =~ s/^.(\\xd8\\xff\\xdb)/\\xff$1/s; return \\$val if $val =~ s/^.(\\xd8\\xff[\\xdb\\xe1])/\\xff$1/s; $$self{PreviewError} = 1 unless $val eq 'none' or $val eq ''; return undef;", // PreviewImage
        ("Sony", 0x202f) => "my ($a,$b,$c) = (Get32u(\\$val,0), Get8u(\\$val,4), Get8u(\\$val,5)); sprintf(\"%.2d%.2d%.2d%.2d %d %d 0x%x\",($a>>17)&0x1f,($a>>12)&0x1f,($a>>6)&0x3f,$a&0x3f,$b,$c,$a>>22);", // PixelShiftInfo
        ("Sony", 0xb000) => "$self->OverrideFileType($$self{TIFF_TYPE} = 'SR2') if $val eq '1 0 0 0'; return $val;", // FileFormat
        ("Sony", 0xb040) => "$val == 65535 ? undef : $val", // Macro
        ("Sony", 0xb041) => "$val == 65535 ? undef : $val", // ExposureMode
        ("Sony", 0xb042) => "$val == 65535 ? undef : $val", // FocusMode
        ("Sony", 0xb043) => "$val == 65535 ? undef : $val", // AFAreaMode
        ("Sony", 0xb044) => "$val == 65535 ? undef : $val", // AFIlluminator
        ("Sony", 0xb047) => "$val == 65535 ? undef : $val", // JPEGQuality
        ("Sony", 0xb048) => "($val == -1 and $$self{Model} =~ /DSLR-A100\\b/) ? undef : $val", // FlashLevel
        ("Sony", 0xb049) => "$val == 65535 ? undef : $val", // ReleaseMode
        ("Sony", 0xb04a) => "$val == 65535 ? undef : $val", // SequenceNumber
        ("Sony", 0xb04b) => "$val == 65535 ? undef : $val", // Anti-Blur
        _ => return None,
    })
}

/// The ValueConv expression ExifTool applies to a MakerNote Main tag.
#[must_use]
pub fn value_conv_expr(maker: &str, tag: u16) -> Option<&'static str> {
    Some(match (maker, tag) {
        ("Apple", 0x0002) => "Image::ExifTool::Apple::ConvertPLIST($val)", // AEMatrix
        ("Apple", 0x003e) => "Image::ExifTool::Apple::ConvertPLIST($val)", // ColorCorrectionMatrix
        ("Apple", 0x0040) => "Image::ExifTool::Apple::ConvertPLIST($val)", // SemanticStyle
        ("Apple", 0x0041) => "Image::ExifTool::Apple::ConvertPLIST($val)", // SemanticStyleRenderingVer
        ("Apple", 0x0042) => "Image::ExifTool::Apple::ConvertPLIST($val)", // SemanticStylePreset
        ("Apple", 0x004e) => "Image::ExifTool::Apple::ConvertPLIST($val)", // Apple_0x004e
        ("Apple", 0x004f) => "Image::ExifTool::Apple::ConvertPLIST($val)", // Apple_0x004f
        ("Apple", 0x0054) => "Image::ExifTool::Apple::ConvertPLIST($val)", // Apple_0x0054
        ("Apple", 0x005a) => "Image::ExifTool::Apple::ConvertPLIST($val)", // Apple_0x005a
        ("Canon", 0x0023) => "$val =~ s/^8 //; $val", // Categories
        ("Canon", 0x0028) => "unpack(\"H*\", $val)", // ImageUniqueID
        ("Canon", 0x00a1) => "length($val) > 64 ? \\$val : $val", // ToneCurveTable
        ("Canon", 0x00a2) => "length($val) > 64 ? \\$val : $val", // SharpnessTable
        ("Canon", 0x00a3) => "length($val) > 64 ? \\$val : $val", // SharpnessFreqTable
        ("Canon", 0x00a4) => "length($val) > 64 ? \\$val : $val", // WhiteBalanceTable
        ("Canon", 0x00b2) => "length($val) > 64 ? \\$val : $val", // ToneCurveMatching
        ("Canon", 0x00b3) => "length($val) > 64 ? \\$val : $val", // WhiteBalanceMatching
        ("Casio", 0x0006) => "$val / 1000", // ObjectDistance
        ("FujiFilm", 0x1044) => "$val / 8", // DigitalZoom
        ("FujiFilm", 0x1438) => "$val & 0x7fff", // ImageCount
        ("Nikon", 0x0001) => "$_=$val; /^[\\x00-\\x09]/ and $_=join(\"\",unpack(\"CCCC\",$_)); $_", // MakerNoteVersion
        ("Nikon", 0x000d) => "my ($a,$b,$c)=unpack(\"c3\",$val); $c ? $a*($b/$c) : 0", // ProgramShift
        ("Nikon", 0x000e) => "my ($a,$b,$c)=unpack(\"c3\",$val); $c ? $a*($b/$c) : 0", // ExposureDifference
        ("Nikon", 0x0012) => "my ($a,$b,$c)=unpack(\"c3\",$val); $c ? $a*($b/$c) : 0", // FlashExposureComp
        ("Nikon", 0x0017) => "my ($a,$b,$c)=unpack(\"c3\",$val); $c ? $a*($b/$c) : 0", // ExternalFlashExposureComp
        ("Nikon", 0x0018) => "my ($a,$b,$c)=unpack(\"c3\",$val); $c ? $a*($b/$c) : 0", // FlashExposureBracketValue
        ("Nikon", 0x001c) => "my ($a,$b,$c)=unpack(\"c3\",$val); $c ? $a*($b/$c) : 0", // ExposureTuning
        ("Nikon", 0x008b) => "my ($a,$b,$c)=unpack(\"C3\",$val); $c ? $a*($b/$c) : 0", // LensFStops
        ("Nikon", 0x009e) => "$val=~s/( 0)+$//; $val", // RetouchHistory
        ("Olympus", 0x0207) => "$val =~ s/\\s+$//; $val", // CameraType
        ("Olympus", 0x1000) => "abs($val)<100 ? 2**(-$val) : 0", // ShutterSpeedValue
        ("Olympus", 0x1001) => "100 * 2 ** ($val - 5)", // ISOValue
        ("Olympus", 0x1002) => "2 ** ($val / 2)", // ApertureValue
        ("Olympus", 0x1017) => "$val=~s/ .*//; $val / 256", // RedBalance
        ("Olympus", 0x1018) => "$val=~s/ .*//; $val / 256", // BlueBalance
        ("Panasonic", 0x0002) => "$val=~/[\\0-\\x2f]/ ? join(\" \",unpack(\"C*\",$val)) : $val", // FirmwareVersion
        ("Panasonic", 0x0023) => "$val / 3", // WhiteBalanceBias
        ("Panasonic", 0x0024) => "$val / 3", // FlashBias
        ("Panasonic", 0x0029) => "$val / 100", // TimeSincePowerOn
        ("Panasonic", 0x0051) => "$val=~s/ +$//; $val", // LensType
        ("Panasonic", 0x0052) => "$val=~s/ +$//; $val", // LensSerialNumber
        ("Panasonic", 0x0053) => "$val=~s/ +$//; $val", // AccessoryType
        ("Panasonic", 0x0054) => "$val=~s/ +$//; $val", // AccessorySerialNumber
        ("Panasonic", 0x0086) => "$val / 10", // ManometerPressure
        ("Panasonic", 0x0090) => "$val / 10", // RollAngle
        ("Panasonic", 0x0091) => "-$val / 10", // PitchAngle
        ("Panasonic", 0x00c5) => "$_=sprintf(\"%.4x\",$val); s/(..)(..)/$2 $1/; $_", // LensTypeModel
        ("Panasonic", 0x00e4) => "$_=sprintf(\"%.4x\",$val); s/(..)(..)/$2 $1/; $_", // LensTypeModel
        ("Pentax", 0x0006) => "length($val)==4 ? sprintf(\"%.4d:%.2d:%.2d\",unpack(\"nC2\",$val)) : \"Unknown ($val)\"", // Date
        ("Pentax", 0x0007) => "length($val)>=3 ? sprintf(\"%.2d:%.2d:%.2d\",unpack(\"C3\",$val)) : \"Unknown ($val)\"", // Time
        ("Pentax", 0x000b) => "(IsInt($val) and $val < 4 and $$self{Model} =~ /Optio 555\\b/) ? $val + 0.1 : $val", // PictureMode
        ("Pentax", 0x0012) => "$val * 1e-5", // ExposureTime
        ("Pentax", 0x0013) => "$val / 10", // FNumber
        ("Pentax", 0x001b) => "$val / 256", // BlueBalance
        ("Pentax", 0x001c) => "$val / 256", // RedBalance
        ("Pentax", 0x001e) => "$val / 100", // DigitalZoom
        ("Pentax", 0x0035) => "my @a=split(\" \",$val); $_/=500 foreach @a; join(\" \",@a)", // SensorSize
        ("Pentax", 0x003c) => "$val & 0x7ff", // AFPointsInFocus
        ("Pentax", 0x0040) => "($val - 50) / 10", // SensitivityAdjust
        ("Pentax", 0x0050) => "53190 - $val", // ColorTemperature
        ("Pentax", 0x005d) => "Image::ExifTool::Pentax::CryptShutterCount($val)", // ShutterCount
        ("Pentax", 0x0203) => "join(\" \",map({ $_/8192 } split(\" \",$val)))", // ColorMatrixA
        ("Pentax", 0x0204) => "join(\" \",map({ $_/8192 } split(\" \",$val)))", // ColorMatrixB
        ("Sigma", 0x000c) => "$val =~ s/Expo:\\s*//, $val", // ExposureCompensation
        ("Sigma", 0x000d) => "$val =~ s/Cont:\\s*//, $val", // Contrast
        ("Sigma", 0x000e) => "$val =~ s/Shad:\\s*//, $val", // Shadow
        ("Sigma", 0x000f) => "$val =~ s/High:\\s*//, $val", // Highlight
        ("Sigma", 0x0010) => "$val =~ s/Satu:\\s*//, $val", // Saturation
        ("Sigma", 0x0011) => "$val =~ s/Shar:\\s*//, $val", // Sharpness
        ("Sigma", 0x0012) => "$val =~ s/Fill:\\s*//, $val", // X3FillLight
        ("Sigma", 0x0014) => "$val =~ s/CC:\\s*//, $val", // ColorAdjustment
        ("Sigma", 0x0016) => "$val =~ s/Qual:\\s*//, $val", // Quality
        ("Sigma", 0x0027) => "$val =~ /^[0-9a-f]+$/i ? hex($val) : $val", // LensType
        ("Sigma", 0x0033) => "$val * 1e-6", // ExposureTime2
        ("Sony", 0x2031) => "$val=~s/(\\d{2})(\\d{2})(\\d{2})(\\d{2})/$4$3$2$1/; $val=~s/^0//; $val", // SerialNumber
        ("Sony", 0x9407) => "PrintHex($val)", // Sony_0x9407
        ("Sony", 0x9408) => "PrintHex($val)", // Sony_0x9408
        ("Sony", 0x9409) => "PrintHex($val)", // Sony_0x9409
        ("Sony", 0x940b) => "PrintHex($val)", // Sony_0x940b
        ("Sony", 0x940d) => "PrintHex($val)", // Sony_0x940d
        ("Sony", 0x940f) => "PrintHex($val)", // Sony_0x940f
        ("Sony", 0x9411) => "PrintHex($val)", // Sony_0x9411
        ("Sony", 0xb02a) => "Image::ExifTool::Sony::ConvLensSpec($val)", // LensSpec
        ("Sony", 0xb02b) => "join(\" \", reverse split(\" \", $val))", // FullImageSize
        ("Sony", 0xb02c) => "join(\" \", reverse split(\" \", $val))", // PreviewImageSize
        _ => return None,
    })
}

/// The PrintConv expression ExifTool applies to a MakerNote Main tag.
#[must_use]
pub fn print_conv_expr(maker: &str, tag: u16) -> Option<&'static str> {
    Some(match (maker, tag) {
        ("Apple", 0x000c) => "my @a = split ' ', $val; sprintf('%.2f - %.2f m', $a[0] <= $a[1] ? @a : reverse @a);", // FocusDistanceRange
        ("Apple", 0x0023) => "my @a=split \" \",$val; sprintf(\"%d %d %d\",$a[0],$a[1]>>28,$a[1]&0xfffffff)", // AFPerformance
        ("Canon", 0x0008) => "$_=$val,s/(\\d+)(\\d{4})/$1-$2/,$_", // FileNumber
        ("Canon", 0x001e) => "my $rev = sprintf(\"%.8x\", $val); my ($rel, $v1, $v2, $r1, $r2) = ($rev =~ /^(.)(.)(..)0?(.+)(..)$/); my %r = ( a => 'Alpha ', b => 'Beta ', '0' => '' ); $rel = defined $r{$rel} ? $r{$rel} : \"Unknown($rel) \"; return \"$rel$v1.$v2 rev $r1.$r2\",", // FirmwareRevision
        ("Canon", 0x0094) => "Image::ExifTool::Canon::PrintAFPoints1D($val)", // AFPointsInFocus1D
        ("Casio", 0x0006) => "\"$val m\"", // ObjectDistance
        ("Casio", 0x0015) => "$_ = $val; if (/^(\\d{2})(\\d{2})\\0\\0(\\d{2})(\\d{2})\\0\\0(\\d{2})(.{2})\\0{2}$/) { my $yr = $1 + ($1 < 70 ? 2000 : 1900); my $sec = $6; $val = \"$yr:$2:$3 $4:$5\"; $val .= \":$sec\" if $sec=~/^\\d{2}$/; return $val; } tr/\\0/./; s/\\.+$//; return \"Unknown ($_)\";", // FirmwareDate
        ("DJI", 0x0003) => "sprintf(\"%+.2f\", $val)", // SpeedX
        ("DJI", 0x0004) => "sprintf(\"%+.2f\", $val)", // SpeedY
        ("DJI", 0x0005) => "sprintf(\"%+.2f\", $val)", // SpeedZ
        ("DJI", 0x0006) => "sprintf(\"%+.2f\", $val)", // Pitch
        ("DJI", 0x0007) => "sprintf(\"%+.2f\", $val)", // Yaw
        ("DJI", 0x0008) => "sprintf(\"%+.2f\", $val)", // Roll
        ("DJI", 0x0009) => "sprintf(\"%+.2f\", $val)", // CameraPitch
        ("DJI", 0x000a) => "sprintf(\"%+.2f\", $val)", // CameraYaw
        ("DJI", 0x000b) => "sprintf(\"%+.2f\", $val)", // CameraRoll
        ("FujiFilm", 0x0010) => "if ($val =~ /^(.*?\\s*)([0-9a-fA-F]*)(\\d{2})(\\d{2})(\\d{2})(.{12})\\s*\\0*$/s and $4 >= 1 and $4 <= 12 and $5 >= 1 and $5 <= 31) { my $yr = $3 + ($3 < 70 ? 2000 : 1900); my $sn = pack 'H*', $2; return \"$1$sn $yr:$4:$5 $6\"; } else { # handle a couple of models which use a slightly different format $val =~ s/\\b(592D(3[0-9])+)/pack(\"H*\",$1).' '/e; } return $val;", // InternalSerialNumber
        ("FujiFilm", 0x100a) => "sprintf(\"Red %+d, Blue %+d\", split(\" \", $val))", // WhiteBalanceFineTune
        ("FujiFilm", 0x1049) => "$val > 0 ? \"+$val\" : $val", // BWAdjustment
        ("FujiFilm", 0x104b) => "$val > 0 ? \"+$val\" : $val", // BWMagentaGreen
        ("FujiFilm", 0x140b) => "\"$val%\"", // AutoDynamicRange
        ("FujiFilm", 0x1446) => "my $on = ((($val >> 8) & 0x0f) == 1) ? 'On' : 'Off'; return sprintf('%s (0x%.4x)', $on, $val);", // FlickerReduction
        ("Nikon", 0x0001) => "$_=$val;s/^(\\d{2})/$1\\./;s/^0//;$_", // MakerNoteVersion
        ("Nikon", 0x0002) => "$_=$val;s/^0 //;s/^1 (\\d+)/Hi $1/;$_", // ISO
        ("Nikon", 0x000d) => "Image::ExifTool::Exif::PrintFraction($val)", // ProgramShift
        ("Nikon", 0x000e) => "$val ? sprintf(\"%+.1f\",$val) : 0", // ExposureDifference
        ("Nikon", 0x0012) => "Image::ExifTool::Exif::PrintFraction($val)", // FlashExposureComp
        ("Nikon", 0x0013) => "$_=$val;s/^0 //;$_", // ISOSetting
        ("Nikon", 0x0017) => "Image::ExifTool::Exif::PrintFraction($val)", // ExternalFlashExposureComp
        ("Nikon", 0x0018) => "sprintf(\"%.1f\",$val)", // FlashExposureBracketValue
        ("Nikon", 0x0019) => "$val !~ /undef/ ? Image::ExifTool::Exif::PrintFraction($val) : \"n/a\"", // ExposureBracketValue
        ("Nikon", 0x001c) => "Image::ExifTool::Exif::PrintFraction($val)", // ExposureTuning
        ("Nikon", 0x0083) => "$_ = $val ? Image::ExifTool::DecodeBits($val, { 0 => 'MF', 1 => 'D', 2 => 'G', 3 => 'VR', 4 => '1', #PH 5 => 'FT-1', #PH/IB 6 => 'E', #PH (electromagnetic aperture mechanism) 7 => 'AF-P', #PH/IB }) : 'AF'; # remove commas and change \"D G\" to just \"G\" s/,//g; s/\\bD G\\b/G/; s/ E\\b// and s/^(G )?/E /; # put \"E\" at the start instead of \"G\" s/ 1// and $_ = \"1 $_\"; # put \"1\" at start s/FT-1 // and $_ .= ' FT-1'; # put \"FT-1\" at end return $_;", // LensType
        ("Nikon", 0x0084) => "Image::ExifTool::Exif::PrintLensInfo($val)", // Lens
        ("Nikon", 0x0089) => "$_ = ''; unless ($val & 0x87) { return 'Single-Frame' unless $val; $_ = 'Single-Frame, '; } return $_ . Image::ExifTool::DecodeBits($val, { 0 => 'Continuous', 1 => 'Delay', 2 => 'PC Control', 3 => 'Self-timer', #forum6281 (NC) 4 => 'Exposure Bracketing', 5 => $$self{Model}=~/D70\\b/ ? 'Unused LE-NR Slowdown' : 'Auto ISO', 6 => 'White-Balance Bracketing', 7 => 'IR Control', 8 => 'D-Lighting Bracketing', #forum6281 (NC) 11 => 'Pre-capture', #28 Z9 pre-release burst });", // ShootingMode
        ("Nikon", 0x008b) => "sprintf(\"%.2f\", $val)", // LensFStops
        ("Nikon", 0x009a) => "$val=~s/ / x /;\"$val um\"", // SensorPixelSize
        ("Nikon", 0x00a7) => "$val == 4294965247 ? \"n/a\" : $val", // ShutterCount
        ("Nikon", 0x00b6) => "$self->ConvertDateTime($val)", // PowerUpTime
        ("Olympus", 0x0204) => "$val=~/\\./ or $val.=\".0\"; $val", // DigitalZoom
        ("Olympus", 0x0205) => "\"$val mm\"", // FocalPlaneDiagonal
        ("Olympus", 0x1000) => "Image::ExifTool::Exif::PrintExposureTime($val)", // ShutterSpeedValue
        ("Olympus", 0x1001) => "int($val * 100 + 0.5) / 100", // ISOValue
        ("Olympus", 0x1002) => "sprintf(\"%.1f\",$val)", // ApertureValue
        ("Olympus", 0x100c) => "\"$val mm\"", // ManualFocusDistance
        ("Panasonic", 0x0002) => "$val=~tr/ /./; $val", // FirmwareVersion
        ("Panasonic", 0x0023) => "Image::ExifTool::Exif::PrintFraction($val)", // WhiteBalanceBias
        ("Panasonic", 0x0024) => "Image::ExifTool::Exif::PrintFraction($val)", // FlashBias
        ("Panasonic", 0x0025) => "return $val unless $val=~/^([A-Z][0-9A-Z]{2})(\\d{2})(\\d{2})(\\d{2})(\\d{4})/; my $yr = $2 + ($2 < 70 ? 2000 : 1900); return \"($1) $yr:$3:$4 no. $5\";", // InternalSerialNumber
        ("Panasonic", 0x0033) => "$val eq \"9999:99:99 00:00:00\" ? \"(not set)\" : $val", // BabyAge
        ("Panasonic", 0x0036) => "$val == 65535 ? \"n/a\" : $val", // TravelDay
        ("Panasonic", 0x004d) => "return 'none' if $val eq '16777216 16777216'; return 'n/a' if $val =~ /^4194303\\.9/; my @a = split ' ', $val; sprintf(\"%.2g %.2g\",@a);", // AFPointPosition
        ("Panasonic", 0x004e) => "length $val", // FaceDetInfo
        ("Panasonic", 0x0060) => "$val=~tr/ /./; $val", // LensFirmwareVersion
        ("Panasonic", 0x0086) => "sprintf(\"%.1f kPa\",$val)", // ManometerPressure
        ("Panasonic", 0x00af) => "$self->ConvertDateTime($val)", // TimeStamp
        ("Panasonic", 0x00de) => "$val =~ /^4194303\\.9/ ? \"n/a\" : $val", // AFAreaSize
        ("Panasonic", 0x8010) => "$val eq \"9999:99:99 00:00:00\" ? \"(not set)\" : $val", // BabyAge
        ("Pentax", 000000) => "$val=~tr/ /./; $val", // PentaxVersion
        ("Pentax", 0x0002) => "$val =~ tr/ /x/; $val", // PreviewImageSize
        ("Pentax", 0x0012) => "$val > 42949 ? \"Unknown (Bulb)\" : Image::ExifTool::Exif::PrintExposureTime($val)", // ExposureTime
        ("Pentax", 0x0013) => "sprintf(\"%.1f\",$val)", // FNumber
        ("Pentax", 0x0027) => "$val=~tr/ /./; $val", // DSPFirmwareVersion
        ("Pentax", 0x0028) => "$val=~tr/ /./; $val", // CPUFirmwareVersion
        ("Pentax", 0x0035) => "sprintf(\"%.3f x %.3f mm\", split(\" \",$val))", // SensorSize
        ("Pentax", 0x0039) => "$_=$val;s/ /x/;$_", // RawImageSize
        ("Pentax", 0x0040) => "$val ? sprintf(\"%+.1f\", $val) : 0", // SensitivityAdjust
        ("Pentax", 0x0047) => "\"$val C\"", // CameraTemperature
        ("Pentax", 0x0203) => "join(\" \",map({sprintf(\"%.5f\",$_)} split(\" \",$val)))", // ColorMatrixA
        ("Pentax", 0x0204) => "join(\" \",map({sprintf(\"%.5f\",$_)} split(\" \",$val)))", // ColorMatrixB
        ("Pentax", 0x03fe) => "\\$val", // DataDump
        ("Pentax", 0x0402) => "\\$val", // ToneCurve
        ("Pentax", 0x0403) => "\\$val", // ToneCurves
        ("Ricoh", 0x0002) => "$val=~/^Rev(\\d+)$/ ? sprintf(\"%.2f\",$1/100) : $val", // FirmwareVersion
        ("Ricoh", 0x100b) => "$val ? sprintf(\"%+.1f\",$val) : 0", // FlashExposureComp
        ("Ricoh", 0x1500) => "sprintf(\"%.1f mm\",$val)", // FocalLength
        ("Sigma", 0x0019) => "$val =~ s/(\\d)of(\\d)/$1 of $2/; $val", // AutoBracket
        ("Sigma", 0x001c) => "$val =~ tr/ /x/; $val", // PreviewImageSize
        ("Sigma", 0x001e) => "$val =~ tr/ /x/; $val", // PreviewImageSize
        ("Sigma", 0x002a) => "$val=~s/ / to /; $val", // LensFocalRange
        ("Sigma", 0x002b) => "$val=~s/ / to /; $val", // LensMaxApertureRange
        ("Sigma", 0x0031) => "sprintf(\"%.1f\",$val)", // FNumber
        ("Sigma", 0x0032) => "Image::ExifTool::Exif::PrintExposureTime($val)", // ExposureTime
        ("Sigma", 0x0033) => "Image::ExifTool::Exif::PrintExposureTime($val)", // ExposureTime2
        ("Sigma", 0x0035) => "$val and $val =~ s/^(\\d)/\\+$1/; $val", // ExposureCompensation
        ("Sigma", 0x0039) => "IsInt($val) ? \"$val C\" : $val", // SensorTemperature
        ("Sigma", 0x0047) => "$val and $val =~ s/^(\\d)/\\+$1/; $val", // ExposureCompensation
        ("Sigma", 0x0049) => "sprintf(\"%.1f\",$val)", // FNumber
        ("Sigma", 0x004a) => "Image::ExifTool::Exif::PrintExposureTime($val)", // ExposureTime
        ("Sigma", 0x004d) => "$val and $val =~ s/^(\\d)/\\+$1/; $val", // ExposureCompensation
        ("Sigma", 0x0055) => "IsInt($val) ? \"$val C\" : $val", // SensorTemperature
        ("Sony", 0x2004) => "$val > 0 ? \"+$val\" : $val", // Contrast
        ("Sony", 0x2005) => "$val > 0 ? \"+$val\" : $val", // Saturation
        ("Sony", 0x2006) => "$val > 0 ? \"+$val\" : $val", // Sharpness
        ("Sony", 0x2007) => "$val > 0 ? \"+$val\" : $val", // Brightness
        ("Sony", 0x2026) => "my @v=split(\" \",$val); $_/=1000 foreach @v; sprintf(\"%.2f %.2f\",$v[0],$v[1])", // WBShiftAB_GM_Precise
        ("Sony", 0x202d) => "$val ? sprintf(\"%+.1f\",$val) : 0", // ExposureStandardAdjustment
        ("Sony", 0x2031) => "sprintf(\"%.8d\",$val)", // SerialNumber
        ("Sony", 0x2032) => "$val > 0 ? \"+$val\" : $val", // Shadows
        ("Sony", 0x2033) => "$val > 0 ? \"+$val\" : $val", // Highlights
        ("Sony", 0x2034) => "$val > 0 ? \"+$val\" : $val", // Fade
        ("Sony", 0x2035) => "$val > 0 ? \"+$val\" : $val", // SharpnessRange
        ("Sony", 0x2036) => "$val > 0 ? \"+$val\" : $val", // Clarity
        ("Sony", 0x2037) => "my @a = split ' ', $val; return $a[2] ? sprintf('%3dx%3d', $a[0], $a[1]) : 'n/a';", // FocusFrameSize
        ("Sony", 0x9407) => "Image::ExifTool::LimitLongValues($val)", // Sony_0x9407
        ("Sony", 0x9408) => "Image::ExifTool::LimitLongValues($val)", // Sony_0x9408
        ("Sony", 0x9409) => "Image::ExifTool::LimitLongValues($val)", // Sony_0x9409
        ("Sony", 0x940b) => "Image::ExifTool::LimitLongValues($val)", // Sony_0x940b
        ("Sony", 0x940d) => "Image::ExifTool::LimitLongValues($val)", // Sony_0x940d
        ("Sony", 0x940f) => "Image::ExifTool::LimitLongValues($val)", // Sony_0x940f
        ("Sony", 0x9411) => "Image::ExifTool::LimitLongValues($val)", // Sony_0x9411
        ("Sony", 0xb021) => "$val ? ($val==0xffffffff ? \"n/a\" : $val) : \"Auto\"", // ColorTemperature
        ("Sony", 0xb02a) => "Image::ExifTool::Sony::PrintLensSpec($val)", // LensSpec
        ("Sony", 0xb02b) => "$val =~ tr/ /x/; $val", // FullImageSize
        ("Sony", 0xb02c) => "$val =~ tr/ /x/; $val", // PreviewImageSize
        _ => return None,
    })
}

/// The bits a MakerNote Main tag names, and how wide each of its words is.
///
/// ExifTool runs DecodeBits over the value with these: each word contributes
/// its own bits, numbered from the word's start, and a value with no bit set
/// prints the table's entry for 0.
///
/// The width in bits, the name of the whole set, and the name of each bit.
pub type Bitmask = (usize, &'static str, &'static [(u32, &'static str)]);

#[must_use]
pub fn bitmask(maker: &str, tag: u16) -> Option<Bitmask> {
    Some(match (maker, tag) {
        ("Apple", 0x0019) => (
            32,
            "",
            &[ // ImageProcessingFlags
        ],
        ),
        ("Apple", 0x0025) => (
            32,
            "",
            &[ // SceneFlags
        ],
        ),
        ("Canon", 0x0023) => (
            32,
            "(none)",
            &[
                // Categories
                (0, "People"),
                (1, "Scenery"),
                (2, "Events"),
                (3, "User 1"),
                (4, "User 2"),
                (5, "User 3"),
                (6, "To Do"),
            ],
        ),
        ("Pentax", 0x000f) => (
            32,
            "(none)",
            &[
                // AFPointsInFocus
                (0, "Top-left"),
                (1, "Top Near-left"),
                (2, "Top"),
                (3, "Top Near-right"),
                (4, "Top-right"),
                (5, "Upper-left"),
                (6, "Upper Near-left"),
                (7, "Upper-middle"),
                (8, "Upper Near-right"),
                (9, "Upper-right"),
                (10, "Far Left"),
                (11, "Left"),
                (12, "Near-left"),
                (13, "Center"),
                (14, "Near-right"),
                (15, "Right"),
                (16, "Far Right"),
                (17, "Lower-left"),
                (18, "Lower Near-left"),
                (19, "Lower-middle"),
                (20, "Lower Near-right"),
                (21, "Lower-right"),
                (22, "Bottom-left"),
                (23, "Bottom Near-left"),
                (24, "Bottom"),
                (25, "Bottom Near-right"),
                (26, "Bottom-right"),
            ],
        ),
        ("Pentax", 0x003c) => (
            32,
            "(none)",
            &[
                // AFPointsInFocus
                (0, "Upper-left"),
                (1, "Top"),
                (2, "Upper-right"),
                (3, "Left"),
                (4, "Mid-left"),
                (5, "Center"),
                (6, "Mid-right"),
                (7, "Right"),
                (8, "Lower-left"),
                (9, "Bottom"),
                (10, "Lower-right"),
            ],
        ),
        ("Sony", 0x2020) => (
            8,
            "(none)",
            &[
                // AFPointsUsed
                (0, "Center"),
                (1, "Top"),
                (2, "Upper-right"),
                (3, "Right"),
                (4, "Lower-right"),
                (5, "Bottom"),
                (6, "Lower-left"),
                (7, "Left"),
                (8, "Upper-left"),
                (9, "Far Right"),
                (10, "Far Left"),
                (11, "Upper-middle"),
                (12, "Near Right"),
                (13, "Lower-middle"),
                (14, "Near Left"),
                (15, "Upper Far Right"),
                (16, "Lower Far Right"),
                (17, "Lower Far Left"),
                (18, "Upper Far Left"),
            ],
        ),
        ("Sony", 0x2022) => (
            8,
            "(none)",
            &[ // FocalPlaneAFPointsUsed
        ],
        ),
        _ => return None,
    })
}

/// The name a MakerNote Main tag stores its value under, for a later
/// conversion to read.
#[must_use]
pub fn data_member(maker: &str, tag: u16) -> Option<&'static str> {
    Some(match (maker, tag) {
        ("Nikon", 0x0034) => "ShutterMode",    // ShutterMode
        ("Olympus", 0x0207) => "CameraType",   // CameraType
        ("Pentax", 0x0005) => "PentaxModelID", // PentaxModelID
        ("Pentax", 0x0006) => "PentaxDate",    // Date
        ("Pentax", 0x0007) => "PentaxTime",    // Time
        ("Pentax", 0x0076) => "FacesDetected", // FaceDetect
        _ => return None,
    })
}

/// The format a MakerNote Main tag declares for itself, and how many
/// elements of it: ExifTool reads the entry that way whatever type the
/// file gives it.
#[must_use]
pub fn format_override(maker: &str, tag: u16) -> Option<(&'static str, usize)> {
    Some(match (maker, tag) {
        ("Canon", 0x0023) => ("int32u", 2),     // Categories
        ("Canon", 0x0028) => ("undef", 1),      // ImageUniqueID
        ("Canon", 0x4002) => ("undef", 1),      // CRWParam
        ("Casio", 0x0015) => ("undef", 18),     // FirmwareDate
        ("FujiFilm", 0x1049) => ("int8s", 1),   // BWAdjustment
        ("FujiFilm", 0x104b) => ("int8s", 1),   // BWMagentaGreen
        ("Minolta", 0x0112) => ("int32s", 1),   // WhiteBalanceFineTune
        ("Olympus", 0x0209) => ("string", 1),   // CameraID
        ("Olympus", 0x0280) => ("undef", 1),    // PreviewImage
        ("Olympus", 0x0400) => ("int16u", 4),   // SensorArea
        ("Olympus", 0x1011) => ("int16s", 9),   // ColorMatrix
        ("Panasonic", 0x0023) => ("int16s", 1), // WhiteBalanceBias
        ("Panasonic", 0x0024) => ("int16s", 1), // FlashBias
        ("Panasonic", 0x0039) => ("int16s", 1), // Contrast
        ("Panasonic", 0x0040) => ("int16s", 1), // Saturation
        ("Panasonic", 0x0041) => ("int16s", 1), // Sharpness
        ("Panasonic", 0x0044) => ("int16u", 1), // ColorTempKelvin
        ("Panasonic", 0x0046) => ("int16s", 1), // WBShiftAB
        ("Panasonic", 0x0047) => ("int16s", 1), // WBShiftGM
        ("Panasonic", 0x0059) => ("int16s", 2), // Transform
        ("Panasonic", 0x0060) => ("int8u", 4),  // LensFirmwareVersion
        ("Panasonic", 0x0063) => ("int8u", 4),  // RecognizedFaceFlags
        ("Panasonic", 0x0065) => ("string", 1), // Title
        ("Panasonic", 0x0066) => ("string", 1), // BabyName
        ("Panasonic", 0x0067) => ("string", 1), // Location
        ("Panasonic", 0x0069) => ("string", 1), // Country
        ("Panasonic", 0x006b) => ("string", 1), // State
        ("Panasonic", 0x006d) => ("string", 1), // City
        ("Panasonic", 0x006f) => ("string", 1), // Landmark
        ("Panasonic", 0x0080) => ("string", 1), // City2
        ("Panasonic", 0x008b) => ("int16s", 1), // WBShiftIntelligentAuto
        ("Panasonic", 0x008c) => ("int16s", 1), // AccelerometerZ
        ("Panasonic", 0x008d) => ("int16s", 1), // AccelerometerX
        ("Panasonic", 0x008e) => ("int16s", 1), // AccelerometerY
        ("Panasonic", 0x0090) => ("int16s", 1), // RollAngle
        ("Panasonic", 0x0091) => ("int16s", 1), // PitchAngle
        ("Panasonic", 0x0092) => ("int8s", 1),  // WBShiftCreativeControl
        ("Panasonic", 0x00a1) => ("int32u", 1), // FilterEffect
        ("Panasonic", 0x00ad) => ("int16s", 2), // HighlightShadow
        ("Panasonic", 0x00bd) => ("int16s", 1), // FocusBracket
        ("Panasonic", 0x00bf) => ("int32u", 2), // PostFocusMerging
        ("Panasonic", 0x8000) => ("undef", 1),  // MakerNoteVersion
        ("Panasonic", 0x8012) => ("int16s", 2), // Transform
        ("Pentax", 0x0015) => ("int16s", 1),    // LightReading
        ("Pentax", 0x0032) => ("int8u", 4),     // ImageEditing
        ("Pentax", 0x0035) => ("int16u", 2),    // SensorSize
        ("Pentax", 0x003c) => ("int32u", 1),    // AFPointsInFocus
        ("Pentax", 0x005c) => ("undef", 1),     // ShakeReductionInfo
        ("Pentax", 0x0060) => ("undef", 1),     // FaceInfo
        ("Pentax", 0x0068) => ("undef", 1),     // AWBInfo
        ("Pentax", 0x0069) => ("int8u", 4),     // DynamicRangeExpansion
        ("Pentax", 0x006b) => ("undef", 1),     // TimeInfo
        ("Pentax", 0x0071) => ("int8u", 1),     // HighISONoiseReduction
        ("Pentax", 0x007d) => ("undef", 1),     // LensCorr
        ("Pentax", 0x0085) => ("int8u", 4),     // HDR
        ("Pentax", 0x0215) => ("undef", 1),     // CameraInfo
        ("Pentax", 0x021c) => ("int16s", 9),    // ColorMatrixA2
        ("Pentax", 0x021d) => ("int16s", 9),    // ColorMatrixB2
        ("Pentax", 0x0235) => ("int8u", 10),    // CrossProcessParams
        ("Ricoh", 0x1004) => ("int16s", 1),     // WhiteBalanceFineTune
        ("Ricoh", 0x1012) => ("int32s", 1),     // Contrast
        ("Samsung", 000000) => ("undef", 8),    // MakerNoteVersion
        ("Sony", 0x0112) => ("int32s", 1),      // WhiteBalanceFineTune
        ("Sony", 0x1000) => ("int8u", 1),       // MultiBurstMode
        ("Sony", 0x200a) => ("int16u", 2),      // HDR
        ("Sony", 0x2037) => ("int16u", 3),      // FocusFrameSize
        ("Sony", 0xb022) => ("int32s", 1),      // ColorCompensationFilter
        ("Sony", 0xb02a) => ("undef", 8),       // LensSpec
        _ => return None,
    })
}
