export default {
  extends: ["@commitlint/config-conventional"],
  rules: {
    // docs/PLAN.md traceability: every commit maps to a phase.
    "scope-enum": [
      2,
      "always",
      [
        "p0",
        "p1",
        "p2",
        "p3",
        "p4",
        "p5",
        "p6",
        "p7",
        "p8",
        "p9",
        "p10",
        "p11",
        "p12",
        "p13",
        "p14",
        "p15",
        "p16",
        "p17",
        "p18",
        "p19",
        "p20",
        "p21",
        "p22",
        "p23",
        "p24",
        "p25",
        "p26",
        "p27",
        "p28",
        "p29",
        "p30",
        "p31",
        "p32",
        "p33",
        // Repo tooling that maps to no PLAN.md phase (linters, CI wiring,
        // dev-dependency gates). Already used in history — `fix(tools)` —
        // just never encoded here, so those commits failed the CI gate.
        "tools",
      ],
    ],
    "scope-empty": [2, "never"],
  },
};
