<?php

declare(strict_types=1);

use SebastianBergmann\CodeCoverage\CodeCoverage;
use SebastianBergmann\CodeCoverage\Driver\Selector;
use SebastianBergmann\CodeCoverage\Filter;
use SebastianBergmann\CodeCoverage\Report\PHP as PhpReport;

$filter_ = new Filter();

$filter_->includeFiles(
    [
        __DIR__ . '/about.php',
        __DIR__ . '/action.php',
        __DIR__ . '/admin.php',
        __DIR__ . '/admin/LocalSiteReader.php',
        __DIR__ . '/admin/album.php',
        __DIR__ . '/admin/album_notification.php',
        __DIR__ . '/admin/albums.php',
        __DIR__ . '/admin/batch_manager.php',
        __DIR__ . '/admin/batch_manager_global.php',
        __DIR__ . '/admin/batch_manager_unit.php',
        __DIR__ . '/admin/cat_list.php',
        __DIR__ . '/admin/cat_modify.php',
        __DIR__ . '/admin/cat_options.php',
        __DIR__ . '/admin/cat_perm.php',
        __DIR__ . '/admin/cat_search.php',
        __DIR__ . '/admin/comments.php',
        __DIR__ . '/admin/configuration.php',
        __DIR__ . '/admin/element_set_ranks.php',
        __DIR__ . '/admin/extend_for_templates.php',
        __DIR__ . '/admin/group_list.php',
        __DIR__ . '/admin/group_perm.php',
        __DIR__ . '/admin/help.php',
        __DIR__ . '/admin/history.php',
        __DIR__ . '/admin/inc/DummyPlugin_maintain.php',
        __DIR__ . '/admin/inc/DummyTheme_maintain.php',
        __DIR__ . '/admin/inc/add_core_tabs.php',
        __DIR__ . '/admin/inc/albums_tab.php',
        __DIR__ . '/admin/inc/c13y_internal.php',
        __DIR__ . '/admin/inc/check_integrity.php',
        __DIR__ . '/admin/inc/configuration_sizes_process.php',
        __DIR__ . '/admin/inc/configuration_watermark_process.php',
        __DIR__ . '/admin/inc/functions_admin.php',
        __DIR__ . '/admin/inc/functions_history.php',
        __DIR__ . '/admin/inc/functions_install.php',
        __DIR__ . '/admin/inc/functions_metadata_admin.php',
        __DIR__ . '/admin/inc/functions_notification_by_mail.php',
        __DIR__ . '/admin/inc/functions_permalinks.php',
        __DIR__ . '/admin/inc/functions_plugins_admin.php',
        __DIR__ . '/admin/inc/functions_upgrade.php',
        __DIR__ . '/admin/inc/functions_upload.php',
        __DIR__ . '/admin/inc/imageInterface.php',
        __DIR__ . '/admin/inc/image_ext_imagick.php',
        __DIR__ . '/admin/inc/image_gd.php',
        __DIR__ . '/admin/inc/image_imagick.php',
        __DIR__ . '/admin/inc/image_vips.php',
        __DIR__ . '/admin/inc/index.php',
        __DIR__ . '/admin/inc/languages.php',
        __DIR__ . '/admin/inc/photos_add_direct_prepare.php',
        __DIR__ . '/admin/inc/plugins.php',
        __DIR__ . '/admin/inc/pwg_image.php',
        __DIR__ . '/admin/inc/tabsheet.php',
        __DIR__ . '/admin/inc/themes.php',
        __DIR__ . '/admin/inc/updates.php',
        __DIR__ . '/admin/inc/user_tabs.php',
        __DIR__ . '/admin/index.php',
        __DIR__ . '/admin/intro.php',
        __DIR__ . '/admin/languages.php',
        __DIR__ . '/admin/languages_installed.php',
        __DIR__ . '/admin/languages_new.php',
        __DIR__ . '/admin/maintenance.php',
        __DIR__ . '/admin/maintenance_actions.php',
        __DIR__ . '/admin/maintenance_env.php',
        __DIR__ . '/admin/menubar.php',
        __DIR__ . '/admin/notification_by_mail.php',
        __DIR__ . '/admin/permalinks.php',
        __DIR__ . '/admin/photo.php',
        __DIR__ . '/admin/photos_add.php',
        __DIR__ . '/admin/photos_add_applications.php',
        __DIR__ . '/admin/photos_add_direct.php',
        __DIR__ . '/admin/photos_add_ftp.php',
        __DIR__ . '/admin/picture_coi.php',
        __DIR__ . '/admin/picture_formats.php',
        __DIR__ . '/admin/picture_modify.php',
        __DIR__ . '/admin/plugin.php',
        __DIR__ . '/admin/plugins.php',
        __DIR__ . '/admin/plugins_installed.php',
        __DIR__ . '/admin/plugins_new.php',
        __DIR__ . '/admin/popuphelp.php',
        __DIR__ . '/admin/profile.php',
        __DIR__ . '/admin/rating.php',
        __DIR__ . '/admin/rating_user.php',
        __DIR__ . '/admin/site_manager.php',
        __DIR__ . '/admin/site_update.php',
        __DIR__ . '/admin/stats.php',
        __DIR__ . '/admin/tags.php',
        __DIR__ . '/admin/theme.php',
        __DIR__ . '/admin/themes.php',
        __DIR__ . '/admin/themes_installed.php',
        __DIR__ . '/admin/themes_new.php',
        __DIR__ . '/admin/updates.php',
        __DIR__ . '/admin/updates_ext.php',
        __DIR__ . '/admin/updates_pwg.php',
        __DIR__ . '/admin/user_activity.php',
        __DIR__ . '/admin/user_list.php',
        __DIR__ . '/admin/user_perm.php',
        __DIR__ . '/comments.php',
        __DIR__ . '/feed.php',
        __DIR__ . '/galleries/index.php',
        __DIR__ . '/i.php',
        __DIR__ . '/identification.php',
        __DIR__ . '/inc/BlockManager.php',
        __DIR__ . '/inc/CalendarBase.php',
        __DIR__ . '/inc/CalendarMonthly.php',
        __DIR__ . '/inc/CalendarWeekly.php',
        __DIR__ . '/inc/Combinable.php',
        __DIR__ . '/inc/Css.php',
        __DIR__ . '/inc/CssLoader.php',
        __DIR__ . '/inc/DerivativeImage.php',
        __DIR__ . '/inc/DerivativeParams.php',
        __DIR__ . '/inc/DisplayBlock.php',
        __DIR__ . '/inc/FileCombiner.php',
        __DIR__ . '/inc/ImageRect.php',
        __DIR__ . '/inc/ImageStdParams.php',
        __DIR__ . '/inc/PersistentCache.php',
        __DIR__ . '/inc/PersistentFileCache.php',
        __DIR__ . '/inc/PluginMaintain.php',
        __DIR__ . '/inc/PwgError.php',
        __DIR__ . '/inc/PwgNamedArray.php',
        __DIR__ . '/inc/PwgNamedStruct.php',
        __DIR__ . '/inc/PwgRequestHandler.php',
        __DIR__ . '/inc/PwgResponseEncoder.php',
        __DIR__ . '/inc/PwgServer.php',
        __DIR__ . '/inc/PwgTemplateAdapter.php',
        __DIR__ . '/inc/QDateRangeScope.php',
        __DIR__ . '/inc/QExpression.php',
        __DIR__ . '/inc/QMultiToken.php',
        __DIR__ . '/inc/QNumericRangeScope.php',
        __DIR__ . '/inc/QResults.php',
        __DIR__ . '/inc/QSearchScope.php',
        __DIR__ . '/inc/QSingleToken.php',
        __DIR__ . '/inc/RegisteredBlock.php',
        __DIR__ . '/inc/Script.php',
        __DIR__ . '/inc/ScriptLoader.php',
        __DIR__ . '/inc/SizingParams.php',
        __DIR__ . '/inc/SrcImage.php',
        __DIR__ . '/inc/Template.php',
        __DIR__ . '/inc/ThemeMaintain.php',
        __DIR__ . '/inc/WatermarkParams.php',
        __DIR__ . '/inc/category_cats.php',
        __DIR__ . '/inc/category_default.php',
        __DIR__ . '/inc/common.php',
        __DIR__ . '/inc/config_default.php',
        __DIR__ . '/inc/constants.php',
        __DIR__ . '/inc/dblayer/functions_mysqli.php',
        __DIR__ . '/inc/dblayer/functions_pgsql.php',
        __DIR__ . '/inc/derivative_params.php',
        __DIR__ . '/inc/derivative_std_params.php',
        __DIR__ . '/inc/filter.php',
        __DIR__ . '/inc/functions.php',
        __DIR__ . '/inc/functions_calendar.php',
        __DIR__ . '/inc/functions_category.php',
        __DIR__ . '/inc/functions_comment.php',
        __DIR__ . '/inc/functions_cookie.php',
        __DIR__ . '/inc/functions_filter.php',
        __DIR__ . '/inc/functions_html.php',
        __DIR__ . '/inc/functions_mail.php',
        __DIR__ . '/inc/functions_metadata.php',
        __DIR__ . '/inc/functions_notification.php',
        __DIR__ . '/inc/functions_picture.php',
        __DIR__ . '/inc/functions_plugins.php',
        __DIR__ . '/inc/functions_rate.php',
        __DIR__ . '/inc/functions_search.php',
        __DIR__ . '/inc/functions_session.php',
        __DIR__ . '/inc/functions_tag.php',
        __DIR__ . '/inc/functions_url.php',
        __DIR__ . '/inc/functions_user.php',
        __DIR__ . '/inc/index.php',
        __DIR__ . '/inc/inflectors/Inflector_en.php',
        __DIR__ . '/inc/menubar.php',
        __DIR__ . '/inc/no_photo_yet.php',
        __DIR__ . '/inc/page_header.php',
        __DIR__ . '/inc/page_tail.php',
        __DIR__ . '/inc/picture_comment.php',
        __DIR__ . '/inc/picture_metadata.php',
        __DIR__ . '/inc/picture_rate.php',
        __DIR__ . '/inc/section_init.php',
        __DIR__ . '/inc/user.php',
        __DIR__ . '/inc/ws_core.php',
        __DIR__ . '/inc/ws_functions.php',
        __DIR__ . '/inc/ws_functions/index.php',
        __DIR__ . '/inc/ws_functions/pwg.php',
        __DIR__ . '/inc/ws_functions/pwg_categories.php',
        __DIR__ . '/inc/ws_functions/pwg_extensions.php',
        __DIR__ . '/inc/ws_functions/pwg_groups.php',
        __DIR__ . '/inc/ws_functions/pwg_images.php',
        __DIR__ . '/inc/ws_functions/pwg_permissions.php',
        __DIR__ . '/inc/ws_functions/pwg_tags.php',
        __DIR__ . '/inc/ws_functions/pwg_users.php',
        __DIR__ . '/inc/ws_init.php',
        __DIR__ . '/inc/ws_protocols/PwgJsonEncoder.php',
        __DIR__ . '/inc/ws_protocols/PwgRestEncoder.php',
        __DIR__ . '/inc/ws_protocols/PwgRestRequestHandler.php',
        __DIR__ . '/inc/ws_protocols/PwgSerialPhpEncoder.php',
        __DIR__ . '/inc/ws_protocols/PwgXmlRpcEncoder.php',
        __DIR__ . '/inc/ws_protocols/PwgXmlWriter.php',
        __DIR__ . '/inc/ws_protocols/index.php',
        __DIR__ . '/index.php',
        __DIR__ . '/install.php',
        __DIR__ . '/install/index.php',
        __DIR__ . '/language/en_UK/admin.lang.php',
        __DIR__ . '/language/en_UK/common.lang.php',
        __DIR__ . '/language/en_UK/index.php',
        __DIR__ . '/language/en_UK/install.lang.php',
        __DIR__ . '/language/en_UK/upgrade.lang.php',
        __DIR__ . '/language/index.php',
        __DIR__ . '/local/config/database.php',
        __DIR__ . '/local/config/index.php',
        __DIR__ . '/local/css/index.php',
        __DIR__ . '/local/index.php',
        __DIR__ . '/local/language/index.php',
        __DIR__ . '/nbm.php',
        __DIR__ . '/notification.php',
        __DIR__ . '/password.php',
        __DIR__ . '/phpinfo.php',
        __DIR__ . '/picture.php',
        __DIR__ . '/plugins/AdminTools/AdminTools_maintain.php',
        __DIR__ . '/plugins/AdminTools/admin.php',
        __DIR__ . '/plugins/AdminTools/index.php',
        __DIR__ . '/plugins/AdminTools/main.php',
        __DIR__ . '/plugins/GDThumb/GDThumb_maintain.php',
        __DIR__ . '/plugins/GDThumb/admin.php',
        __DIR__ . '/plugins/GDThumb/changelog.php',
        __DIR__ . '/plugins/GDThumb/config_default.php',
        __DIR__ . '/plugins/GDThumb/functions_GDThumb.php',
        __DIR__ . '/plugins/GDThumb/index.php',
        __DIR__ . '/plugins/GDThumb/main.php',
        __DIR__ . '/plugins/LocalFilesEditor/LocalFilesEditor_maintain.php',
        __DIR__ . '/plugins/LocalFilesEditor/admin.php',
        __DIR__ . '/plugins/LocalFilesEditor/index.php',
        __DIR__ . '/plugins/LocalFilesEditor/main.php',
        __DIR__ . '/plugins/LocalFilesEditor/show_default.php',
        __DIR__ . '/plugins/TakeATour/admin.php',
        __DIR__ . '/plugins/TakeATour/functions_TakeATour.php',
        __DIR__ . '/plugins/TakeATour/main.php',
        __DIR__ . '/plugins/index.php',
        __DIR__ . '/plugins/language_switch/index.php',
        __DIR__ . '/plugins/language_switch/language_switch.php',
        __DIR__ . '/plugins/language_switch/main.php',
        __DIR__ . '/plugins/rv_tscroller/RVTS.php',
        __DIR__ . '/plugins/rv_tscroller/main.php',
        __DIR__ . '/popuphelp.php',
        __DIR__ . '/profile.php',
        __DIR__ . '/qsearch.php',
        __DIR__ . '/random.php',
        __DIR__ . '/register.php',
        __DIR__ . '/search.php',
        __DIR__ . '/tags.php',
        __DIR__ . '/template-extension/index.php',
        __DIR__ . '/template-extension/yoga/index.php',
        __DIR__ . '/themes/bootstrap_darkroom/index.php',
        __DIR__ . '/themes/bootstrap_darkroom/themeconf.php',
        __DIR__ . '/themes/default/index.php',
        __DIR__ . '/themes/default/themeconf.php',
        __DIR__ . '/themes/elegant/index.php',
        __DIR__ . '/themes/elegant/themeconf.php',
        __DIR__ . '/themes/index.php',
        __DIR__ . '/themes/modus/functions_modus.php',
        __DIR__ . '/themes/modus/index.php',
        __DIR__ . '/themes/modus/themeconf.php',
        __DIR__ . '/themes/smartpocket/SPThumbPicker.php',
        __DIR__ . '/themes/smartpocket/functions_smartpocket.php',
        __DIR__ . '/themes/smartpocket/themeconf.php',
        __DIR__ . '/upgrade.php',
        __DIR__ . '/upgrade_feed.php',
        __DIR__ . '/ws.php',
    ]
);

$coverage_ = new CodeCoverage(
    new Selector()
        ->forLineCoverage($filter_),
    $filter_
);
$coverage_->excludeUncoveredFiles();

$coverage_->start($_SERVER['REQUEST_URI']);

function save_coverage(): void
{
    global $coverage_;
    $coverage_->stop();
    new PhpReport()
        ->process($coverage_, 'C:/Apache24/logs/xdebug/coverage/' . bin2hex(random_bytes(16)) . '.cov');
}

register_shutdown_function(save_coverage(...));
