import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

// Prettier is deliberately NOT wired in here (no eslint-plugin-prettier) — same
// separation of concerns P0 kept between ECS (style) and PHPStan (correctness).
// `bun run format` runs Prettier standalone; this config is lint rules only.
export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "_data/**",
      "vendor/**",
      // Bundled third-party JS (verified per-file — docs/PLAN.md P1).
      // `themes/default/js/ui/**` and the top-level jquery.js/.min.js/
      // .cookie.js files are gone entirely (docs/PLAN.md P46's vendor-CDN
      // migration retargeted them to CDN URLs) -- `plugins/**` still has
      // one real file left, `jquery.progressbar.min.js` (kept only as a
      // real-file-on-disk fixture for 2 unit tests, never loaded by any
      // page -- see `ThemeBaseAssets`'s own P49-C removal note), plus
      // first-party selectize theme CSS. `jquery.geoip.js` (P49-B group 1)
      // and the other 2 of this comment's former "3 genuinely unresolvable
      // vendored libraries" (`jquery.cluetip`/`jquery.Jcrop`, later ported
      // to `vendor/cluetip.ts`/`vendor/jcrop.ts`, P49-C) are gone from disk
      // entirely, so this ignore list no longer needs an entry for any of
      // them.
      "themes/default/js/plugins/**",
      // Generated by `bun run generate:api-client`, not hand-maintained.
      "openapi/client/schema.d.ts",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.{js,mjs,cjs}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          // A `catch (_e)` binding is neither a var nor an arg to this
          // rule, so the two patterns above do not reach it -- the
          // `_`-means-intentional convention has to be stated a third time
          // or every deliberately-ignored catch warns.
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      eqeqeq: "error",
      "no-implicit-coercion": "error",
      "no-param-reassign": ["warn", { props: false }],
    },
  },
  {
    // `.mjs` is an ES module by definition, so the `sourceType: "script"`
    // above cannot apply to it -- it makes every `import` a parse error.
    // Node-only build tooling, so no browser or jQuery globals.
    files: ["**/*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...globals.node,
      },
    },
  },
  {
    files: ["**/*.ts"],
    extends: [...tseslint.configs.strictTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    // P47 (real type-design pass, following P46's own "same code, same
    // behavior" mechanical conversion) narrowed themes/**/*.ts's `any`
    // usage from 782+ sites down to 6 files with a real, deliberately-
    // irreducible remainder each documents inline: `search_filters.ts`/
    // `mcs.ts` (a genuinely heterogeneous, deferred-to-P48 nested
    // search-filter query object -- `global_params`/`fullname_of_cat`
    // and mcs.ts's own consumers of them), `history.ts` (the same
    // family, read from a saved search's own `searchDetails`),
    // `common.ts` (a `Array.prototype` polyfill guard and `sprintf`'s
    // own genuinely-polymorphic format-spec argument), `datepicker.ts`
    // (jQuery UI's own datepicker internals this file's `pwgDatepicker`
    // plugin patches, no real upstream type source), and `profile.ts`
    // (`setInfos`'s callback, whose real shape differs per dispatched
    // endpoint). `build/ambient-globals.d.ts` keeps the same relaxation
    // too, though for different entries now: every vendor-library type
    // it used to need this for (jquery-confirm/cluetip/Jcrop/DataTables/
    // jgrowl/ajaxmanager/sort/autogrow-textarea/plupload/Chart.js/
    // moment) is gone, each ported to a native module in turn (P49-B/
    // P49-C). What remains is `global_params`/`fullname_of_cat` (the
    // same search-filter query object as `search_filters.ts`'s own
    // entry above, declared ambiently here for `Window`) and
    // `AlbumSelectorCallbackArgs.addSelectedAlbum`'s own real variadic
    // passthrough.
    files: [
      "themes/default/js/search_filters.ts",
      "themes/default/js/mcs.ts",
      "themes/admin/default/js/history.ts",
      "themes/admin/default/js/common.ts",
      "themes/admin/default/js/datepicker.ts",
      "themes/standard_pages/js/profile.ts",
      "build/ambient-globals.d.ts",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },
  {
    // KNOWN GAP, measured rather than assumed: the base rules in the
    // plain-JS block above (`eqeqeq`, `no-console`, `no-implicit-coercion`,
    // `no-param-reassign`) are scoped to `**/*.{js,mjs,cjs}`, which is 8
    // tooling files. The 93 `.ts` files that are the actual application get
    // none of them. Turning them on for `.ts` costs, measured: eqeqeq 389,
    // no-console 56, no-param-reassign 31, no-implicit-coercion 22.
    //
    // `eqeqeq` is the one worth real work, and it is not a mechanical
    // `==` -> `===` sweep: several comparisons here are deliberately loose
    // because an id arrives as a number from one endpoint and a string from
    // another (album_selector's `c.id != cat_id`), so each site needs
    // reading. Its own commit, not a rider on a config change.
    // Match the plain-JS block's own `^_`-prefixed-means-intentionally-
    // unused convention (see the `no-unused-vars` rule above) --
    // `recommendedTypeChecked` enables `@typescript-eslint/no-unused-vars`
    // with no ignore pattern of its own, which is a real inconsistency
    // with the rest of this config once .ts files exist to lint (P46-B).
    files: ["**/*.ts"],
    rules: {
      // `strictTypeChecked` above turns on ~20 rules beyond
      // `recommendedTypeChecked`, and the tree is clean under all of them
      // except the five opted out here. Each carries the violation count
      // measured when it was disabled, so the cost of adopting it later is
      // a fact rather than a guess -- and so a future reader can tell a
      // deliberate exclusion from an unexamined one.

      // 464 violations. The `!` assertion is this codebase's normal way of
      // stating an invariant the type system cannot see (a template always
      // renders the element, an id is always in range), usually with a
      // comment. Banning it would replace them with `as` casts, which are
      // strictly worse: they also silence genuine type errors.
      "@typescript-eslint/no-non-null-assertion": "off",

      // 396. Almost entirely `"text " + number` when building markup or a
      // URL, which is idiomatic and safe.
      "@typescript-eslint/restrict-plus-operands": "off",

      // 251, and essentially all of them are jQuery APIs that P49 is in the
      // middle of removing. Worth revisiting once that phase lands, when
      // the count should be near zero on its own.
      "@typescript-eslint/no-deprecated": "off",

      // 58. `${number}` in a template literal; noise here.
      "@typescript-eslint/restrict-template-expressions": "off",

      // 44, and it is the one rule on this list that is *unsafe* to act on
      // here rather than merely noisy. It trusts the declared types, and
      // this codebase's types are partly assertions -- `!` in 464 places,
      // `as` casts, and ambient declarations for jQuery plugins with no
      // real type source. "Always truthy according to the type" is
      // therefore not "always truthy at runtime", and the fixes it asks for
      // delete real runtime guards: `toaster.ts`'s check that its caller
      // passed a text and an icon, `addAlbum.ts`'s check that the plugin
      // was given a cache. It also produces outright false positives
      // against closure mutation -- it reports `dom.ts`'s `if (stopped)` as
      // always false, though `stopped` is set by the `stopPropagation`
      // wrapper installed a few lines above. Revisit when the ambient
      // jQuery declarations are gone.
      "@typescript-eslint/no-unnecessary-condition": "off",

      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          // See the plain-JS block: `catch (_e)` needs its own pattern.
          caughtErrorsIgnorePattern: "^_",
        },
      ],
    },
  },
);
