import type { ESLint, Linter } from "eslint";
import { defineConfig } from "eslint/config";
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";
import sonarjs from "eslint-plugin-sonarjs";

// Prettier is deliberately NOT wired in here (no eslint-plugin-prettier) — same
// separation of concerns P0 kept between ECS (style) and PHPStan (correctness).
// `bun run format` runs Prettier standalone; this config is lint rules only.
// `defineConfig()` (ESLint core), not `tseslint.config()` -- the latter is
// deprecated in favor of the former now that ESLint core provides the same
// config-flattening/`extends` support natively.
export default defineConfig(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "_data/**",
      "vendor/**",
      // Bundled third-party JS: `jquery.progressbar.min.js`, kept only as
      // a real-file-on-disk fixture for 2 unit tests, never loaded by any
      // page, plus first-party selectize theme CSS.
      "themes/default/js/plugins/**",
      // Generated by `bun run generate:api-client`, not hand-maintained.
      "openapi/client/schema.d.ts",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.{js,mjs,cjs}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    rules: {
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          // A `catch (_e)` binding is neither a var nor an arg to this
          // rule, so the two patterns above do not reach it -- the
          // `_`-means-intentional convention has to be stated a third time
          // or every deliberately-ignored catch warns.
          caughtErrorsIgnorePattern: "^_",
        },
      ],
      eqeqeq: "error",
      "no-implicit-coercion": "error",
      "no-param-reassign": ["warn", { props: false }],
    },
  },
  {
    // `.mjs` is an ES module by definition, so the `sourceType: "script"`
    // above cannot apply to it -- it makes every `import` a parse error.
    // Node-only build tooling, so no browser or jQuery globals.
    files: ["**/*.mjs"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...globals.node,
      },
    },
  },
  {
    files: ["**/*.ts"],
    extends: [...tseslint.configs.strictTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    // P47 (real type-design pass, following P46's own "same code, same
    // behavior" mechanical conversion) narrowed themes/**/*.ts's `any`
    // usage from 782+ sites down to 5 files with a real, deliberately-
    // irreducible remainder each documents inline: `search_filters.ts`/
    // `mcs.ts` (a genuinely heterogeneous, deferred-to-P48 nested
    // search-filter query object -- `global_params`/`fullname_of_cat`
    // and mcs.ts's own consumers of them), `history.ts` (the same
    // family, read from a saved search's own `searchDetails`),
    // `sprintf.ts` (`sprintf`'s own genuinely-polymorphic format-spec
    // argument -- split out of `common.ts` at P51-I, which otherwise
    // has zero remaining `any` since P51-H already deleted its own
    // `Array.prototype` polyfill guard), and `profile.ts` (`setInfos`'s
    // callback, whose real shape differs per dispatched endpoint).
    // `build/ambient-globals.d.ts` keeps the same relaxation too, for
    // its own real remaining `AlbumSelectorCallbackArgs.addSelectedAlbum`
    // variadic passthrough (P51-H deleted its own former
    // `global_params`/`fullname_of_cat` entries, confirmed-dead once
    // `mcs.ts` started importing the real, typed exports directly).
    files: [
      "themes/default/js/mcs.ts",
      "themes/admin/default/js/history.ts",
      "themes/default/js/sprintf.ts",
      "themes/standard_pages/js/profile.ts",
      "build/ambient-globals.d.ts",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },
  {
    // P51-A: the 14.x branch's own hardened ruleset (`git show
    // origin/14.x:eslint.config.js`), adopted here now that P49 (jQuery
    // removal) has landed -- the rules `strictTypeChecked` left opted out
    // above were each blocked on exactly that. Also closes the gap the
    // plain-JS block's `eqeqeq`/`no-console`/`no-implicit-coercion`/
    // `no-param-reassign` never reached: those rules were scoped to
    // `**/*.{js,mjs,cjs}` (8 tooling files), never extended to the 108
    // real `.ts` files that are the actual application.
    // Match the plain-JS block's own `^_`-prefixed-means-intentionally-
    // unused convention (see the `no-unused-vars` rule above) --
    // `recommendedTypeChecked` enables `@typescript-eslint/no-unused-vars`
    // with no ignore pattern of its own, which is a real inconsistency
    // with the rest of this config once .ts files exist to lint (P46-B).
    files: ["**/*.ts"],
    rules: {
      // Tracked rather than silenced (14.x: "warn", not "off"). The `!`
      // assertion is this codebase's normal way of stating an invariant
      // the type system cannot see (a template always renders the
      // element, an id is always in range), usually with a comment.
      // Banning it outright would replace real assertions with `as`
      // casts, which are strictly worse: they also silence genuine type
      // errors.
      "@typescript-eslint/no-non-null-assertion": "warn",

      "@typescript-eslint/restrict-plus-operands": "error",

      "@typescript-eslint/restrict-template-expressions": [
        "error",
        { allowNumber: true, allowBoolean: false, allowNullish: false },
      ],

      // Real modern-DOM-API replacements now that jQuery (and the ambient
      // vendor typings it needed) is gone (P49): `keyCode`/`which` ->
      // `event.key`/`event.code`, `srcElement` -> `event.target`,
      // `window.event` -> an explicit event parameter, `substr` ->
      // `.slice()`/`.substring()`, `unescape` -> `decodeURIComponent`.
      "@typescript-eslint/no-deprecated": "error",

      // Read per-site, not blanket-suppressed: some are real bugs the
      // same way P47/P49 found them this way; a genuine false positive
      // from closure mutation (documented at its one confirmed site,
      // `dom.ts`'s `stopped` check) gets a targeted, commented
      // `eslint-disable-next-line`, never a default off.
      "@typescript-eslint/no-unnecessary-condition": "error",

      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          // See the plain-JS block: `catch (_e)` needs its own pattern.
          caughtErrorsIgnorePattern: "^_",
        },
      ],

      eqeqeq: ["error", "always", { null: "ignore" }],
      "no-console": ["error", { allow: ["warn", "error"] }],
      "no-implicit-coercion": "error",
      "no-param-reassign": ["error", { props: false }],
      "prefer-const": "error",
      "@typescript-eslint/prefer-nullish-coalescing": [
        "error",
        { ignorePrimitives: { string: true } },
      ],
      "@typescript-eslint/no-confusing-void-expression": "error",
      "@typescript-eslint/no-invalid-void-type": [
        "error",
        { allowAsThisParameter: true },
      ],

      // Beyond 14.x's own ruleset -- `tsconfig.json` already sets
      // `verbatimModuleSyntax: true`, which `consistent-type-imports`
      // directly supports (a type-only import re-exported as a value
      // would break isolated per-file transpilation).
      "@typescript-eslint/consistent-type-imports": [
        "error",
        { fixStyle: "inline-type-imports" },
      ],
      "@typescript-eslint/consistent-type-exports": "error",
      "@typescript-eslint/no-import-type-side-effects": "error",

      "@typescript-eslint/no-floating-promises": "error",
      "@typescript-eslint/no-misused-promises": "error",

      // A `default` case counts as covering the rest of the union even
      // for a type this rule would otherwise want every member listed
      // for -- most of this codebase's switches rely on that.
      "@typescript-eslint/switch-exhaustiveness-check": [
        "error",
        { considerDefaultExhaustiveForUnions: true },
      ],

      "@typescript-eslint/no-shadow": "error",
      "@typescript-eslint/strict-boolean-expressions": "error",
      "@typescript-eslint/no-unnecessary-type-assertion": "error",
      "@typescript-eslint/require-array-sort-compare": "error",
      "@typescript-eslint/prefer-readonly": "error",
      "@typescript-eslint/default-param-last": "error",
      "@typescript-eslint/no-unnecessary-qualifier": "error",
      "@typescript-eslint/no-empty-interface": "error",
      "@typescript-eslint/no-redeclare": "error",
      "@typescript-eslint/no-dupe-class-members": "error",
      "@typescript-eslint/prefer-optional-chain": "error",
      "@typescript-eslint/prefer-for-of": "error",
      "@typescript-eslint/class-methods-use-this": "error",
      "@typescript-eslint/no-loop-func": "error",
      "@typescript-eslint/no-empty-function": "error",
      "@typescript-eslint/prefer-includes": "error",
      "@typescript-eslint/prefer-string-starts-ends-with": "error",
      "@typescript-eslint/consistent-return": "error",
      "@typescript-eslint/prefer-regexp-exec": "error",
      "@typescript-eslint/prefer-find": "error",
      "@typescript-eslint/no-confusing-non-null-assertion": "error",
      "@typescript-eslint/no-useless-empty-export": "error",
      "@typescript-eslint/no-unsafe-type-assertion": "error",
      "@typescript-eslint/no-use-before-define": [
        "error",
        { functions: false },
      ],

      // Zero real violations at the time each was measured -- pure
      // forward-guards / free consistency wins, no fix population.
      "@typescript-eslint/no-unused-private-class-members": "error",
      "@typescript-eslint/consistent-type-assertions": "error",
      "@typescript-eslint/array-type": "error",
      "@typescript-eslint/class-literal-property-style": "error",
      "@typescript-eslint/consistent-generic-constructors": "error",
      "@typescript-eslint/consistent-indexed-object-style": "error",
      "@typescript-eslint/no-inferrable-types": "error",
      "@typescript-eslint/dot-notation": "error",
      "@typescript-eslint/promise-function-async": "error",
      "@typescript-eslint/prefer-destructuring": "error",
      // jQuery is fully gone (P49); guard against it ever coming back as
      // a dependency now that nothing in this config would otherwise
      // notice a reintroduced import.
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          paths: [
            {
              name: "jquery",
              message: "jQuery was removed in P49 -- use vendor/utils/dom.ts.",
            },
          ],
        },
      ],
    },
  },
  {
    // P51-M: eslint-plugin-sonarjs's own `recommended` config, adopted in
    // full (measured at 119 real sites across 29 rules against the
    // P51-A–L-final tree) -- small, genuinely bug/security-focused
    // (ReDoS, hardcoded passwords, identical functions, ignored
    // exceptions), unlike eslint-plugin-unicorn's `recommended` (4,314
    // sites, mostly fighting this codebase's own deliberate conventions
    // -- see docs/PLAN.md's own P51-M entry for the full analysis).
    // Spread directly (not `extends: [...]`) -- eslint-plugin-sonarjs's own
    // `recommended` config object's types are too loose for this project's
    // `exactOptionalPropertyTypes` to accept through ESLint's own
    // `ExtendsElement` type. Its real runtime shape (confirmed directly
    // against the installed package) is a single flat
    // `{name, plugins, rules, settings}` object, never the array branch its
    // own union type also allows -- narrowed with an explicit cast.
    files: ["**/*.ts"],
    ...(() => {
      // eslint-disable-next-line @typescript-eslint/no-unsafe-type-assertion, @typescript-eslint/no-non-null-assertion -- see comment above; eslint-plugin-sonarjs's own `configs` index signature is untyped, and `recommended` is confirmed to be the flat object shape, not its own type's array alternative.
      const recommended = sonarjs.configs!["recommended"] as {
        plugins: Record<string, ESLint.Plugin>;
        rules: Linter.RulesRecord;
      };

      return {
        plugins: recommended.plugins,
        rules: {
          ...recommended.rules,
          // Pure duplicate of the already-configured
          // `@typescript-eslint/no-unused-vars` above, minus its own
          // `argsIgnorePattern`/`varsIgnorePattern`/
          // `caughtErrorsIgnorePattern` (this codebase's established
          // `^_`-means-intentionally-unused convention) -- sonarjs's own
          // rule takes no options at all (confirmed against its schema),
          // so it would re-flag every deliberately-`_`-prefixed name the
          // real rule already accepts.
          "sonarjs/no-unused-vars": "off",
        },
      };
    })(),
  },
);
