import js from "@eslint/js";
import tseslint from "typescript-eslint";
import globals from "globals";

// Prettier is deliberately NOT wired in here (no eslint-plugin-prettier) — same
// separation of concerns P0 kept between ECS (style) and PHPStan (correctness).
// `bun run format` runs Prettier standalone; this config is lint rules only.
export default tseslint.config(
  {
    ignores: [
      "dist/**",
      "node_modules/**",
      "_data/**",
      "vendor/**",
      // Bundled third-party JS (verified per-file — docs/PLAN.md P1).
      // `themes/default/js/ui/**` and the top-level jquery.js/.min.js/
      // .cookie.js files are gone entirely (docs/PLAN.md P46's vendor-CDN
      // migration retargeted them to CDN URLs) -- `plugins/**` still has
      // real files left (3 genuinely unresolvable vendored libraries,
      // plus first-party selectize theme CSS).
      "themes/default/js/plugins/**",
      "themes/admin/default/js/jquery.geoip.js",
      // Generated by `bun run generate:api-client`, not hand-maintained.
      "openapi/client/schema.d.ts",
    ],
  },
  js.configs.recommended,
  {
    files: ["**/*.{js,mjs,cjs}"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        ...globals.browser,
        ...globals.jquery,
        ...globals.node,
      },
    },
    rules: {
      "no-console": ["warn", { allow: ["warn", "error"] }],
      "no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      eqeqeq: "error",
      "no-implicit-coercion": "error",
      "no-param-reassign": ["warn", { props: false }],
    },
  },
  {
    files: ["**/*.ts"],
    extends: [...tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    // P47 (real type-design pass, following P46's own "same code, same
    // behavior" mechanical conversion) narrowed themes/**/*.ts's `any`
    // usage from 782+ sites down to 6 files with a real, deliberately-
    // irreducible remainder each documents inline: `search_filters.ts`/
    // `mcs.ts` (a genuinely heterogeneous, deferred-to-P48 nested
    // search-filter query object -- `global_params`/`fullname_of_cat`
    // and mcs.ts's own consumers of them), `history.ts` (the same
    // family, read from a saved search's own `searchDetails`),
    // `common.ts` (a `Array.prototype` polyfill guard and `sprintf`'s
    // own genuinely-polymorphic format-spec argument), `datepicker.ts`
    // (jQuery UI's own datepicker internals this file's `pwgDatepicker`
    // plugin patches, no real upstream type source), and `profile.ts`
    // (`setInfos`'s callback, whose real shape differs per dispatched
    // endpoint). `build/jquery-plugins.d.ts` keeps the same relaxation
    // for its own remaining confirmed-unsourced vendor entries
    // (jquery-confirm/cluetip/Jcrop/jgrowl/ajaxmanager/progressbar/
    // sort/autogrow-textarea/DataTables -- no real npm/CDN type
    // package covers any of them).
    files: [
      "themes/default/js/search_filters.ts",
      "themes/default/js/mcs.ts",
      "themes/admin/default/js/history.ts",
      "themes/admin/default/js/common.ts",
      "themes/admin/default/js/datepicker.ts",
      "themes/standard_pages/js/profile.ts",
      "build/jquery-plugins.d.ts",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-return": "off",
    },
  },
  {
    // album_selector.ts's own P48 module conversion (docs/PLAN.md) --
    // real consumers of its `AlbumSelector` class, imported through the
    // `?dup` suffix (build/vite-modules.d.ts's own ambient ``declare
    // module "*album_selector?dup"`` with real named re-exports, Design
    // §4). `tsc --noEmit` resolves this cleanly (confirmed directly,
    // clean end-to-end), but typescript-eslint's own `projectService`
    // does not resolve the same ambient wildcard module the same way
    // `tsc` does (confirmed directly: every real `AlbumSelector` usage
    // in these files reports as "unsafe call/member access on an error
    // type" under `eslint`, even though the exact same code type-checks
    // fine under `tsc`) -- a real tool divergence, not a real type-safety
    // gap, so only the 4 rules that misfire from it are relaxed here,
    // not `no-explicit-any` (unlike the P47 block above, nothing in
    // these files is a real, deliberate `any`). mcs.ts's own copy of
    // this same usage needs no entry here -- already covered by the
    // broader P47 block above.
    files: [
      "themes/admin/default/js/batchManagerFilter.ts",
      "themes/admin/default/js/batchManagerGlobal.ts",
      "themes/admin/default/js/batchManagerUnit.ts",
      "themes/admin/default/js/cat_modify.ts",
      "themes/admin/default/js/cat_search.ts",
      "themes/admin/default/js/photos_add_direct.ts",
      "themes/admin/default/js/picture_modify.ts",
    ],
    rules: {
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-call": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
    },
  },
  {
    // Match the plain-JS block's own `^_`-prefixed-means-intentionally-
    // unused convention (see the `no-unused-vars` rule above) --
    // `recommendedTypeChecked` enables `@typescript-eslint/no-unused-vars`
    // with no ignore pattern of its own, which is a real inconsistency
    // with the rest of this config once .ts files exist to lint (P46-B).
    files: ["**/*.ts"],
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
    },
  },
);
