<?php

declare(strict_types=1);

namespace Piwigo\Controller\Api\Images;

/**
 * Generated by tools/openapi-generate-input-dto.php from
 * openapi/openapi.yaml's own 'imageSetMd5sum' operation -- do not hand-edit
 * without also updating the spec, or re-run the generator instead.
 */
final readonly class ImageSetMd5sumInput
{
    public function __construct(
        public int $blockSize,
    ) {}

    /**
     * @param array<int|string, mixed> $raw
     */
    public static function fromArray(array $raw): self
    {
        $blockSize = $raw['blockSize'] ?? null;

        return new self(
            blockSize: is_int($blockSize) ? $blockSize : 0,
        );
    }
}
