<?php

declare(strict_types=1);

namespace Piwigo\Controller\Api\Images;

/**
 * Generated by tools/openapi-generate-input-dto.php from
 * openapi/openapi.yaml's own 'imageMissingDerivatives' operation -- do not hand-edit
 * without also updating the spec, or re-run the generator instead.
 */
final readonly class ImageMissingDerivativesInput
{
    /**
     * @param list<string> $types
     * @param list<int> $ids
     */
    public function __construct(
        public array $types,
        public array $ids,
        public int $maxUrls,
        public ?int $prevPage,
    ) {}

    /**
     * @param array<int|string, mixed> $raw
     */
    public static function fromArray(array $raw): self
    {
        $types = $raw['types'] ?? null;
        $ids = $raw['ids'] ?? null;
        $maxUrls = $raw['maxUrls'] ?? null;
        $prevPage = $raw['prevPage'] ?? null;

        return new self(
            types: self::typesList($types),
            ids: self::idsList($ids),
            maxUrls: is_int($maxUrls) ? $maxUrls : 200,
            prevPage: is_int($prevPage) ? $prevPage : null,
        );
    }

    /**
     * @return list<string>
     */
    private static function typesList(mixed $raw): array
    {
        if (! is_array($raw)) {
            return [];
        }

        $values = [];
        foreach ($raw as $v) {
            $narrowed = is_string($v) ? $v : null;
            if ($narrowed !== null) {
                $values[] = $narrowed;
            }
        }

        return $values;
    }

    /**
     * @return list<int>
     */
    private static function idsList(mixed $raw): array
    {
        if (! is_array($raw)) {
            return [];
        }

        $values = [];
        foreach ($raw as $v) {
            $narrowed = is_int($v) ? $v : (is_numeric($v) ? (int) $v : null);
            if ($narrowed !== null) {
                $values[] = $narrowed;
            }
        }

        return $values;
    }
}
