import * as path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
export const REPO_ROOT = path.resolve(__dirname, '../../..');

/**
 * Single source of truth for credentials used across e2e specs.
 *
 * The username/password here MUST match what the SQL fixture
 * `dev/fixtures/piwigo-17.0.sql` seeds (it's the same fixture the
 * integration suite loads). global-setup.ts reloads the fixture before
 * every full e2e run, so the install state is rebuilt to a known shape
 * and both suites stay in agreement.
 *
 * If you change the fixture's admin user, change this too.
 */
export const TEST_DATA = {
    admin: { username: 'fixture_admin', password: 'fixture_admin' },
};

/**
 * Test image paths. These files are generated by global-setup.ts before
 * any spec runs — never commit actual images to the repo.
 */
export const TEST_PHOTOS = Array.from({ length: 10 }, (_, i) =>
    path.join(REPO_ROOT, 'galleries', 'Wallpapers', `${String(i + 1).padStart(3, '0')}.jpg`)
);
