<?php

declare(strict_types=1);

// +-----------------------------------------------------------------------+
// | This file is part of Piwigo.                                          |
// |                                                                       |
// | For copyright and license information, please view the COPYING.txt    |
// | file that was distributed with this source code.                      |
// +-----------------------------------------------------------------------+

namespace Piwigo\Migrations;

use Doctrine\DBAL\Platforms\AbstractMySQLPlatform;
use Doctrine\DBAL\Platforms\PostgreSQLPlatform;
use Doctrine\DBAL\Platforms\SQLitePlatform;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use LogicException;
use Override;

/**
 * [P44-L] Adds `password_reset_requests`, the request-scoped rate-limit
 * table backing `Piwigo\Auth\PasswordResetRequestRepository` -- read and
 * written by `Controller\PasswordController::processVerificationCode()`
 * to close the gap where nothing previously limited how often a fresh
 * verification code could be requested (only the per-code 3-attempt
 * guess lockout was limited). Same dual-scope (per-account AND per-IP)
 * shape as the baseline's own `user_failed_logins` table -- see
 * `Version20260804122301`'s own docblock for that precedent -- added here
 * as its own migration rather than folded into the baseline, since this
 * table didn't exist in the schema that baseline snapshots.
 */
final class Version20260822153000 extends AbstractMigration
{
    #[Override]
    public function getDescription(): string
    {
        return '[P44-L] Add password_reset_requests, rate-limiting table for reset-code requests';
    }

    #[Override]
    public function up(Schema $schema): void
    {
        if ($this->platform instanceof PostgreSQLPlatform) {
            $this->upPostgres();

            return;
        }

        if ($this->platform instanceof AbstractMySQLPlatform) {
            $this->upMysql();

            return;
        }

        if ($this->platform instanceof SQLitePlatform) {
            $this->upSqlite();

            return;
        }

        throw new LogicException(self::class . ' has no migration path for platform ' . $this->platform::class);
    }

    #[Override]
    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE password_reset_requests');
    }

    private function upMysql(): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE `password_reset_requests` (
              `id` int NOT NULL AUTO_INCREMENT COMMENT 'surrogate primary key',
              `user_id` int DEFAULT NULL COMMENT 'targeted user id, if the submitted username/email resolved to a real account',
              `ip` varchar(45) NOT NULL COMMENT 'REMOTE_ADDR the reset-code request came from',
              `requested_at` DATETIME NOT NULL COMMENT 'when the reset-code request occurred',
              PRIMARY KEY (`id`),
              KEY `idx_password_reset_requests_user_time` (`user_id`, `requested_at`),
              KEY `idx_password_reset_requests_ip_time` (`ip`, `requested_at`),
              CONSTRAINT `fk_password_reset_requests_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='password-reset-code requests, read and written by PasswordController::processVerificationCode() via PasswordResetRequestRepository to rate-limit how often a fresh code can be requested'
            SQL);
    }

    private function upPostgres(): void
    {
        $this->addSql(
            'CREATE TABLE password_reset_requests (' .
            'id integer GENERATED BY DEFAULT AS IDENTITY, ' .
            'user_id integer DEFAULT NULL, ' .
            'ip varchar(45) NOT NULL, ' .
            'requested_at timestamp NOT NULL, ' .
            'PRIMARY KEY (id))'
        );
        $this->addSql('CREATE INDEX idx_password_reset_requests_user_time ON password_reset_requests (user_id, requested_at)');
        $this->addSql('CREATE INDEX idx_password_reset_requests_ip_time ON password_reset_requests (ip, requested_at)');
        $this->addSql('ALTER TABLE password_reset_requests ADD CONSTRAINT fk_password_reset_requests_user_id FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE');
        $this->addSql("COMMENT ON TABLE password_reset_requests IS 'password-reset-code requests, read and written by PasswordController::processVerificationCode() via PasswordResetRequestRepository to rate-limit how often a fresh code can be requested'");
        $this->addSql("COMMENT ON COLUMN password_reset_requests.id IS 'surrogate primary key'");
        $this->addSql("COMMENT ON COLUMN password_reset_requests.user_id IS 'targeted user id, if the submitted username/email resolved to a real account'");
        $this->addSql("COMMENT ON COLUMN password_reset_requests.ip IS 'REMOTE_ADDR the reset-code request came from'");
        $this->addSql("COMMENT ON COLUMN password_reset_requests.requested_at IS 'when the reset-code request occurred'");
    }

    private function upSqlite(): void
    {
        $this->addSql(
            'CREATE TABLE password_reset_requests (' .
            'id INTEGER PRIMARY KEY, ' .
            'user_id INTEGER DEFAULT NULL REFERENCES users(id) ON DELETE CASCADE, ' .
            'ip VARCHAR(45) NOT NULL, ' .
            'requested_at DATETIME NOT NULL)'
        );
        $this->addSql('CREATE INDEX idx_password_reset_requests_user_time ON password_reset_requests (user_id, requested_at)');
        $this->addSql('CREATE INDEX idx_password_reset_requests_ip_time ON password_reset_requests (ip, requested_at)');
    }
}
