<?php

declare(strict_types=1);

// +-----------------------------------------------------------------------+
// | This file is part of Piwigo.                                          |
// |                                                                       |
// | For copyright and license information, please view the COPYING.txt    |
// | file that was distributed with this source code.                      |
// +-----------------------------------------------------------------------+

namespace Piwigo\Ws\Images;

use Override;
use Piwigo\Common\ValueObject\ImageId;
use Piwigo\Core\CurrentLogger;
use Piwigo\Core\Paths;
use Piwigo\Core\UrlServiceInterface;
use Piwigo\Image\ImagePathHelper;
use Piwigo\Image\ImageService;
use Piwigo\Ws\WsAction;
use Piwigo\Ws\WsErrorResponse;

/**
 * `pwg.images.checkFiles` -- checks if a file has been updated.
 */
final readonly class CheckFilesHandler implements WsAction
{
    public function __construct(
        private ImageService $imageService,
        private CurrentLogger $currentLogger,
        private UrlServiceInterface $urlService,
        private Paths $paths,
    ) {}

    /**
     * @param array<mixed> $params
     * @return WsErrorResponse|array<string, string>
     */
    #[Override]
    public function __invoke(array $params): WsErrorResponse|array
    {
        $input = CheckFilesParams::fromArray($params);

        $logger = $this->currentLogger->get();

        $logger->debug('checkFiles', 'WS', $params);

        $path = $this->imageService->getPathById(ImageId::from($input->imageId));

        if ($path === null) {
            return new WsErrorResponse(404, 'image_id not found');
        }
        // `path` is stored root-relative (e.g. "upload/2026/.../foo.jpg") --
        // resolve it to a real filesystem path the same way
        // FormatsDeleteHandler/DerivativeImage do (ImagePathHelper::
        // getElementPath()), rather than handing the bare DB value straight
        // to md5_file() below, which silently fails (false, never equal to
        // any real hash) for every non-remote photo.
        $path = ImagePathHelper::getElementPath(
            [
                'path' => $path,
            ],
            $this->urlService,
            $this->paths
        );

        $ret = [];

        if ($input->thumbnailSum !== null) {
            // We always say the thumbnail is equal to create no reaction on the
            // other side. Since Piwigo 2.4 and derivatives, the thumbnails and web
            // sizes are always generated by Piwigo
            $ret['thumbnail'] = 'equals';
        }

        $compare_type = null;
        $compare_sum = null;
        if ($input->highSum !== null) {
            $ret['file'] = 'equals';
            $compare_type = 'high';
            $compare_sum = $input->highSum;
        } elseif ($input->fileSum !== null) {
            $compare_type = 'file';
            $compare_sum = $input->fileSum;
        }

        if ($compare_type !== null) {
            $path_md5sum = md5_file($path);
            $logger->debug('checkFiles, md5_file($path) = ' . ($path_md5sum === false ? '' : $path_md5sum), 'WS');
            if ($path_md5sum !== $compare_sum) {
                $ret[$compare_type] = 'differs';
            } else {
                $ret[$compare_type] = 'equals';
            }
        }

        $logger->debug('checkFiles', 'WS', $ret);

        return $ret;
    }
}
