<?php

declare(strict_types=1);

namespace Piwigo\Tools\PhpStan\Latte;

/**
 * Writes/updates a `{varType}` block declaring every template variable's
 * inferred type (IDE autocompletion only -- Latte compiles `{varType}` to a
 * literal empty string, see vendor/latte/latte/src/Latte/Essential/Nodes/
 * VarTypeNode.php) directly into the real `.latte` source, sourced from the
 * same VariableMap LatteTemplateCompiler::injectVarDocblocks() already uses
 * for the compiled-output `@var` docblocks -- so this can never drift from
 * that mechanism the way a hand-written `{varType}` pass would.
 *
 * The block is delimited by sentinel Latte comments (compile to nothing) so
 * re-runs can find and replace it instead of duplicating or hand-editing:
 *
 *   {* BEGIN varType (auto-generated by `composer lint:vartype:fix` -- do not hand-edit) *}
 *   {varType \Piwigo\Foo\Bar $current}
 *   {* END varType *}
 *
 * A template declaring `{templateType FooView}` (`VariableMapBuilder`'s own
 * mechanism for that) owns its own IDE-hint declaration already -- this
 * class leaves it alone rather than prepending a second, redundant block.
 */
final class VarTypeSyncer
{
    private const string BEGIN_MARKER = '{* BEGIN varType';

    private const string END_MARKER = '{* END varType *}';

    private const string BEGIN_LINE = '{* BEGIN varType (auto-generated by `composer lint:vartype:fix` -- do not hand-edit) *}';

    private const string BLOCK_PATTERN = '/\{\* BEGIN varType.*?\{\* END varType \*\}\n?/s';

    private const string TEMPLATE_TYPE_PATTERN = '/\{templateType\s+[^\s}]+\}/';

    /**
     * @param array<string, string> $vars template variable name => PHPStan type string
     */
    public function sync(string $rawSource, array $vars, string $templateRealPath): VarTypeSyncResult
    {
        if (preg_match(self::TEMPLATE_TYPE_PATTERN, $rawSource) === 1) {
            return new VarTypeSyncResult($rawSource, false, []);
        }

        $notices = [];
        $lines = [];
        foreach ($vars as $name => $type) {
            if (preg_match('/^[a-zA-Z_][a-zA-Z0-9_]*$/', $name) !== 1) {
                $notices[] = "variable name '{$name}' in {$templateRealPath} is not a valid PHP identifier -- skipped (extract() skips it at runtime too)";
                continue;
            }
            $lines[] = "{varType {$type} \${$name}}";
        }

        $hasExistingBlock = str_contains($rawSource, self::BEGIN_MARKER);

        if ($lines === []) {
            $content = $hasExistingBlock
                ? preg_replace(self::BLOCK_PATTERN, '', $rawSource) ?? $rawSource
                : $rawSource;

            return new VarTypeSyncResult($content, $content !== $rawSource, $notices);
        }

        $block = self::BEGIN_LINE . "\n" . implode("\n", $lines) . "\n" . self::END_MARKER . "\n";

        $content = $hasExistingBlock
            ? preg_replace(self::BLOCK_PATTERN, $block, $rawSource, 1) ?? $rawSource
            : $block . $rawSource;

        return new VarTypeSyncResult($content, $content !== $rawSource, $notices);
    }
}
