-- Create the trigger function
CREATE OR REPLACE FUNCTION update_lastmodified_column()
RETURNS TRIGGER AS $$
BEGIN
   NEW.lastmodified = now();
   RETURN NEW;
END;
$$ language 'plpgsql';

-- FTS trigger functions: populate tsvector columns on INSERT and UPDATE.
-- These fire during COPY FROM STDIN, so bulk inserts populate FTS automatically.

CREATE OR REPLACE FUNCTION update_images_fts()
RETURNS TRIGGER AS $$
BEGIN
    NEW.image_fts := to_tsvector('english',
        coalesce(NEW.name, '') || ' ' || coalesce(NEW.comment, ''));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_categories_fts()
RETURNS TRIGGER AS $$
BEGIN
    NEW.category_fts := to_tsvector('english',
        coalesce(NEW.name, '') || ' ' || coalesce(NEW.comment, ''));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_tags_fts()
RETURNS TRIGGER AS $$
BEGIN
    NEW.tag_fts := to_tsvector('english', coalesce(NEW.name, ''));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

--
-- Table structure for table `activity`
--

CREATE TABLE activity
(
    activity_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object       VARCHAR(255) NOT NULL,
    object_id    INTEGER      NOT NULL,
    action       VARCHAR(255) NOT NULL,
    performed_by INTEGER      NOT NULL,
    session_idx  VARCHAR(255) NOT NULL,
    ip_address   INET                     DEFAULT NULL,
    occurred_on  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    details      VARCHAR(255)             DEFAULT NULL,
    user_agent   VARCHAR(255)             DEFAULT NULL
);

--
-- Table structure for table `caddie`
--

CREATE TABLE caddie
(
    user_id    INTEGER NOT NULL,
    element_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, element_id)
);

--
-- Table structure for table `categories`
--

CREATE TYPE categories_status AS ENUM ('public', 'private');

CREATE TABLE categories
(
    id                        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                      VARCHAR(255)      NOT NULL,
    id_uppercat               BIGINT                     DEFAULT NULL,
    comment                   TEXT,
    dir                       VARCHAR(255)               DEFAULT NULL,
    sort_rank                 INTEGER                    DEFAULT NULL,
    status                    categories_status NOT NULL DEFAULT 'public',
    site_id                   INTEGER,
    visible                   BOOLEAN           NOT NULL DEFAULT true,
    representative_picture_id INTEGER                    DEFAULT NULL,
    uppercats                 VARCHAR(255),
    commentable               BOOLEAN           NOT NULL DEFAULT true,
    global_rank               VARCHAR(255)               DEFAULT NULL,
    image_order               VARCHAR(128)               DEFAULT NULL,
    permalink                 VARCHAR(64)                DEFAULT NULL UNIQUE,
    lastmodified              TIMESTAMP WITH TIME ZONE   DEFAULT CURRENT_TIMESTAMP,
    category_fts              TSVECTOR
);

CREATE INDEX idx_categories_id_uppercat ON categories (id_uppercat);
CREATE INDEX idx_categories_lastmodified ON categories (lastmodified);

CREATE INDEX category_ft ON categories USING GIN(category_fts);

CREATE TRIGGER trg_categories_update_lastmodified
    BEFORE UPDATE
    ON categories
    FOR EACH ROW EXECUTE FUNCTION update_lastmodified_column();

CREATE TRIGGER trg_categories_fts
    BEFORE INSERT OR UPDATE OF name, comment
    ON categories
    FOR EACH ROW EXECUTE FUNCTION update_categories_fts();

--
-- Table structure for table `comments`
--

CREATE TABLE comments
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id        INTEGER                  NOT NULL,
    date            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    author          VARCHAR(255)                      DEFAULT NULL,
    email           VARCHAR(255)                      DEFAULT NULL,
    author_id       INTEGER                           DEFAULT NULL,
    anonymous_id    VARCHAR(45)              NOT NULL,
    website_url     VARCHAR(255)                      DEFAULT NULL,
    content         TEXT,
    validated       BOOLEAN                  NOT NULL DEFAULT false,
    validation_date TIMESTAMP WITH TIME ZONE          DEFAULT NULL
);

CREATE INDEX idx_comments_image_id ON comments (image_id);
CREATE INDEX idx_comments_validation_date ON comments (validation_date);

--
-- Table structure for table `config`
--

CREATE TABLE config
(
    param   VARCHAR(40) PRIMARY KEY,
    value   TEXT,
    comment VARCHAR(255) DEFAULT NULL
);

--
-- Table structure for table `favorites`
--

CREATE TABLE favorites
(
    user_id  INTEGER NOT NULL,
    image_id INTEGER NOT NULL,
    PRIMARY KEY (user_id, image_id)
);

--
-- Table structure for table `group_access`
--

CREATE TABLE group_access
(
    group_id INTEGER NOT NULL,
    cat_id   INTEGER NOT NULL,
    PRIMARY KEY (group_id, cat_id)
);

--
-- Table structure for table `user_groups`
--

CREATE TABLE user_groups
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL UNIQUE,
    is_default   BOOLEAN      NOT NULL    DEFAULT false,
    lastmodified TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_groups_lastmodified ON user_groups (lastmodified);

CREATE TRIGGER trg_user_groups_update_lastmodified
    BEFORE UPDATE
    ON user_groups
    FOR EACH ROW EXECUTE FUNCTION update_lastmodified_column();

--
-- Table structure for table `history`
--

CREATE TYPE history_section AS ENUM ('categories', 'tags', 'search', 'list', 'favorites', 'most_visited', 'best_rated', 'recent_pics', 'recent_cats');

CREATE TYPE history_image_type AS ENUM ('picture', 'high', 'other');

CREATE TABLE history
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        DATE    NOT NULL,
    time        TIME WITHOUT TIME ZONE NOT NULL,
    user_id     INTEGER NOT NULL,
    IP          INET    NOT NULL,
    section     history_section    DEFAULT NULL,
    category_id INTEGER            DEFAULT NULL,
    search_id   INTEGER            DEFAULT NULL,
    tag_ids     VARCHAR(50)        DEFAULT NULL,
    image_id    INTEGER            DEFAULT NULL,
    image_type  history_image_type DEFAULT NULL,
    format_id   INTEGER            DEFAULT NULL,
    auth_key_id INTEGER            DEFAULT NULL
);

--
-- Table structure for table `history_summary`
--

CREATE TABLE history_summary
(
    year            INTEGER NOT NULL,
    month           INTEGER DEFAULT NULL,
    day             INTEGER DEFAULT NULL,
    hour            INTEGER DEFAULT NULL,
    nb_pages        INTEGER DEFAULT NULL,
    history_id_from INTEGER DEFAULT NULL,
    history_id_to   INTEGER DEFAULT NULL,
    UNIQUE (year, month, day, hour)
);

--
-- Table structure for table `image_category`
--

CREATE TABLE image_category
(
    image_id    INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    sort_rank   INTEGER DEFAULT NULL,
    PRIMARY KEY (image_id, category_id)
);

CREATE INDEX idx_image_category_category_id ON image_category (category_id);

--
-- Table structure for table `image_format`
--

CREATE TABLE image_format
(
    format_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_id  INTEGER      NOT NULL,
    ext       VARCHAR(255) NOT NULL,
    filesize  INTEGER DEFAULT NULL
);

--
-- Table structure for table `image_tag`
--

CREATE TABLE image_tag
(
    image_id INTEGER NOT NULL,
    tag_id   INTEGER NOT NULL,
    PRIMARY KEY (image_id, tag_id)
);

CREATE INDEX idx_image_tag_tag_id ON image_tag (tag_id);

--
-- Table structure for table `images`
--

CREATE TABLE images
(
    id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file                 VARCHAR(255)             NOT NULL,
    date_available       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_creation        TIMESTAMP WITH TIME ZONE          DEFAULT NULL,
    name                 VARCHAR(255)                      DEFAULT NULL,
    comment              TEXT,
    author               VARCHAR(255)                      DEFAULT NULL,
    hit                  INTEGER                  NOT NULL DEFAULT 0,
    filesize             INTEGER                           DEFAULT NULL,
    width                INTEGER                           DEFAULT NULL,
    height               INTEGER                           DEFAULT NULL,
    coi                  CHAR(4)                           DEFAULT NULL,
    representative_ext   VARCHAR(4)                        DEFAULT NULL,
    date_metadata_update DATE                              DEFAULT NULL,
    rating_score         REAL                              DEFAULT NULL,
    path                 VARCHAR(600)             NOT NULL,
    storage_category_id  INTEGER                           DEFAULT NULL,
    level                INTEGER                  NOT NULL DEFAULT 0,
    md5sum               CHAR(32)                          DEFAULT NULL,
    added_by             INTEGER                  NOT NULL,
    rotation             INTEGER                           DEFAULT NULL,
    latitude             DOUBLE PRECISION                  DEFAULT NULL,
    longitude            DOUBLE PRECISION                  DEFAULT NULL,
    lastmodified         TIMESTAMP WITH TIME ZONE          DEFAULT CURRENT_TIMESTAMP,
    image_fts            TSVECTOR
);

CREATE INDEX idx_images_storage_category_id ON images (storage_category_id);
CREATE INDEX idx_images_date_available ON images (date_available);
CREATE INDEX idx_images_rating_score ON images (rating_score);
CREATE INDEX idx_images_hit ON images (hit);
CREATE INDEX idx_images_date_creation ON images (date_creation);
CREATE INDEX idx_images_latitude ON images (latitude);
CREATE INDEX idx_images_path ON images (path);
CREATE INDEX idx_images_lastmodified ON images (lastmodified);

CREATE INDEX image_ft ON images USING GIN(image_fts);

COMMENT
ON COLUMN images.coi IS 'center of interest';

CREATE TRIGGER trg_images_update_lastmodified
    BEFORE UPDATE
    ON images
    FOR EACH ROW EXECUTE FUNCTION update_lastmodified_column();

CREATE TRIGGER trg_images_fts
    BEFORE INSERT OR UPDATE OF name, comment
    ON images
    FOR EACH ROW EXECUTE FUNCTION update_images_fts();

--
-- Table structure for table `languages`
--

CREATE TABLE languages
(
    id      VARCHAR(64) PRIMARY KEY,
    version VARCHAR(64) NOT NULL,
    name    VARCHAR(64) DEFAULT NULL
);

--
-- Table structure for table `lounge`
--

CREATE TABLE lounge
(
    image_id    INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    PRIMARY KEY (image_id, category_id)
);

--
-- Table structure for table `old_permalinks`
--

CREATE TABLE old_permalinks
(
    cat_id       INTEGER                  NOT NULL,
    permalink    VARCHAR(64) PRIMARY KEY,
    date_deleted TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_hit     TIMESTAMP WITH TIME ZONE          DEFAULT NULL,
    hit          INTEGER                  NOT NULL
);

--
-- Table structure for table `plugins`
--

CREATE TYPE plugins_state AS ENUM ('inactive', 'active');

CREATE TABLE plugins
(
    id      VARCHAR(64) PRIMARY KEY,
    state   plugins_state NOT NULL DEFAULT 'inactive',
    version VARCHAR(64)   NOT NULL
);

--
-- Table structure for table `rate`
--

CREATE TABLE rate
(
    user_id      INTEGER     NOT NULL,
    element_id   INTEGER     NOT NULL,
    anonymous_id VARCHAR(45) NOT NULL,
    rate         INTEGER     NOT NULL,
    date         DATE        NOT NULL,
    PRIMARY KEY (element_id, user_id, anonymous_id)
);

--
-- Table structure for table `search`
--

CREATE TABLE search
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    search_uuid CHAR(23)                 DEFAULT NULL,
    created_on  TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    created_by  INTEGER                  DEFAULT NULL,
    forked_from INTEGER                  DEFAULT NULL,
    rules       TEXT
);

--
-- Table structure for table `sessions`
--

CREATE TABLE sessions
(
    id         VARCHAR(255) PRIMARY KEY,
    data       TEXT                     NOT NULL,
    expiration TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--
-- Table structure for table `sites`
--

CREATE TABLE sites
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    galleries_url VARCHAR(255) NOT NULL UNIQUE
);

--
-- Table structure for table `tags`
--

CREATE TABLE tags
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    url_name     VARCHAR(255) NOT NULL,
    lastmodified TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    tag_fts      TSVECTOR
);

CREATE INDEX idx_tags_url_name ON tags (url_name);
CREATE INDEX idx_tags_lastmodified ON tags (lastmodified);

CREATE INDEX tag_name_ft ON tags USING GIN(tag_fts);

CREATE TRIGGER trg_tags_update_lastmodified
    BEFORE UPDATE
    ON tags
    FOR EACH ROW EXECUTE FUNCTION update_lastmodified_column();

CREATE TRIGGER trg_tags_fts
    BEFORE INSERT OR UPDATE OF name
    ON tags
    FOR EACH ROW EXECUTE FUNCTION update_tags_fts();

--
-- Table structure for table `themes`
--

CREATE TABLE themes
(
    id      VARCHAR(64) PRIMARY KEY,
    version VARCHAR(64) NOT NULL,
    name    VARCHAR(64) DEFAULT NULL
);

--
-- Table structure for table `upgrade`
--

CREATE TABLE upgrade
(
    id          VARCHAR(20) PRIMARY KEY,
    applied     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description VARCHAR(255)                      DEFAULT NULL
);

--
-- Table structure for table `user_access`
--

CREATE TABLE user_access
(
    user_id INTEGER NOT NULL,
    cat_id  INTEGER NOT NULL,
    PRIMARY KEY (user_id, cat_id)
);

--
-- Table structure for table `user_auth_keys`
--

CREATE TABLE user_auth_keys
(
    auth_key_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_key    VARCHAR(255)             NOT NULL,
    user_id     INTEGER                  NOT NULL,
    created_on  TIMESTAMP WITH TIME ZONE NOT NULL,
    duration    INTEGER DEFAULT NULL,
    expired_on  TIMESTAMP WITH TIME ZONE NOT NULL
);

--
-- Table structure for table `user_cache`
--

CREATE TYPE user_cache_image_access_type AS ENUM ('NOT IN', 'IN');

CREATE TABLE user_cache
(
    user_id               INTEGER PRIMARY KEY,
    need_update           BOOLEAN                      NOT NULL DEFAULT true,
    cache_update_time     INTEGER                      NOT NULL,
    forbidden_categories  TEXT,
    nb_total_images       INTEGER                               DEFAULT NULL,
    last_photo_date       TIMESTAMP WITH TIME ZONE              DEFAULT NULL,
    nb_available_tags     INTEGER                               DEFAULT NULL,
    nb_available_comments INTEGER                               DEFAULT NULL,
    image_access_type     user_cache_image_access_type NOT NULL DEFAULT 'NOT IN',
    image_access_list     TEXT                                  DEFAULT NULL
);

--
-- Table structure for table `user_cache_categories`
--

CREATE TABLE user_cache_categories
(
    user_id                        INTEGER NOT NULL,
    cat_id                         INTEGER NOT NULL,
    date_last                      TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    max_date_last                  TIMESTAMP WITH TIME ZONE DEFAULT NULL,
    nb_images                      INTEGER NOT NULL,
    count_images                   INTEGER                  DEFAULT 0,
    nb_categories                  INTEGER                  DEFAULT 0,
    count_categories               INTEGER                  DEFAULT 0,
    user_representative_picture_id INTEGER                  DEFAULT NULL,
    PRIMARY KEY (user_id, cat_id)
);

--
-- Table structure for table `user_feed`
--

CREATE TABLE user_feed
(
    id         VARCHAR(50) PRIMARY KEY,
    user_id    INTEGER NOT NULL,
    last_check TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

--
-- Table structure for table `user_group`
--

CREATE TABLE user_group
(
    user_id  INTEGER NOT NULL,
    group_id INTEGER NOT NULL,
    PRIMARY KEY (group_id, user_id)
);

--
-- Table structure for table `user_infos`
--

CREATE TYPE user_infos_status AS ENUM ('webmaster', 'admin', 'normal', 'generic', 'guest');

CREATE TABLE user_infos
(
    user_id                 INTEGER PRIMARY KEY,
    nb_image_page           INTEGER                  NOT NULL DEFAULT 80,
    status                  user_infos_status        NOT NULL DEFAULT 'guest',
    language                VARCHAR(50)              NOT NULL,
    expand                  BOOLEAN                  NOT NULL DEFAULT false,
    show_nb_comments        BOOLEAN                  NOT NULL DEFAULT false,
    show_nb_hits            BOOLEAN                  NOT NULL DEFAULT false,
    recent_period           INTEGER                  NOT NULL DEFAULT 7,
    theme                   VARCHAR(255)             NOT NULL DEFAULT 'modus',
    registration_date       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    enabled_high            BOOLEAN                  NOT NULL DEFAULT true,
    level                   INTEGER                  NOT NULL,
    activation_key          VARCHAR(255)                      DEFAULT NULL,
    activation_key_expire   TIMESTAMP WITH TIME ZONE          DEFAULT NULL,
    last_visit              TIMESTAMP WITH TIME ZONE          DEFAULT NULL,
    last_visit_from_history BOOLEAN                  NOT NULL DEFAULT false,
    lastmodified            TIMESTAMP WITH TIME ZONE          DEFAULT CURRENT_TIMESTAMP,
    preferences             TEXT                              DEFAULT NULL
);

CREATE INDEX idx_user_infos_lastmodified ON user_infos (lastmodified);

CREATE TRIGGER trg_user_infos_update_lastmodified
    BEFORE UPDATE
    ON user_infos
    FOR EACH ROW EXECUTE FUNCTION update_lastmodified_column();

--
-- Table structure for table `user_mail_notification`
--

CREATE TABLE user_mail_notification
(
    user_id   INTEGER PRIMARY KEY,
    check_key VARCHAR(16) NOT NULL UNIQUE,
    enabled   BOOLEAN     NOT NULL     DEFAULT false,
    last_send TIMESTAMP WITH TIME ZONE DEFAULT NULL
);

--
-- Table structure for table `users`
--

CREATE TABLE users
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(100) NOT NULL UNIQUE,
    password     VARCHAR(255) DEFAULT NULL,
    mail_address VARCHAR(255) DEFAULT NULL
);
