--
-- PostgreSQL database dump
--

\restrict R07nQK1U9NwWmxgEEuQwObQUO53RVlPhRQEJtRzetl51ciiFikVG9IT8HZjWu2N

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: piwigo_activity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_activity (
    activity_id integer NOT NULL,
    object character varying(255) NOT NULL,
    object_id integer NOT NULL,
    action character varying(255) NOT NULL,
    performed_by integer,
    session_idx character varying(255) NOT NULL,
    ip_address character varying(50) DEFAULT NULL::character varying,
    occured_on timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    details character varying(255) DEFAULT NULL::character varying,
    user_agent character varying(255) DEFAULT NULL::character varying
);

--
-- Name: piwigo_activity_activity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_activity ALTER COLUMN activity_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_activity_activity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_caddie; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_caddie (
    user_id integer NOT NULL,
    element_id integer NOT NULL,
    CONSTRAINT chk_caddie_element_id_unsigned CHECK ((element_id >= 0))
);

--
-- Name: piwigo_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_categories (
    id smallint NOT NULL,
    name character varying(255) NOT NULL,
    id_uppercat smallint,
    comment text,
    dir character varying(255) DEFAULT NULL::character varying,
    rank smallint,
    status character varying(8) NOT NULL,
    site_id smallint,
    visible character varying(8) NOT NULL,
    representative_picture_id integer,
    uppercats character varying(255) NOT NULL,
    commentable character varying(8) NOT NULL,
    global_rank character varying(255) DEFAULT NULL::character varying,
    image_order character varying(128) DEFAULT NULL::character varying,
    permalink character varying(64) DEFAULT NULL::character varying,
    lastmodified timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);

--
-- Name: piwigo_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_comments (
    id integer NOT NULL,
    image_id integer NOT NULL,
    date timestamp(0) without time zone NOT NULL,
    author character varying(255) DEFAULT NULL::character varying,
    email character varying(255) DEFAULT NULL::character varying,
    author_id integer,
    anonymous_id character varying(45) NOT NULL,
    website_url character varying(255) DEFAULT NULL::character varying,
    content text,
    validated character varying(8) NOT NULL,
    validation_date timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);

--
-- Name: piwigo_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_config; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_config (
    param character varying(40) NOT NULL,
    value text,
    comment character varying(255) DEFAULT NULL::character varying
);

--
-- Name: piwigo_derivative_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_derivative_settings (
    id smallint NOT NULL,
    default_quality integer DEFAULT 95 NOT NULL,
    watermark_json json NOT NULL,
    custom_json json NOT NULL
);

--
-- Name: piwigo_derivative_size; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_derivative_size (
    name character varying(32) NOT NULL,
    enabled smallint DEFAULT 1 NOT NULL,
    max_width integer DEFAULT 0 NOT NULL,
    max_height integer DEFAULT 0 NOT NULL,
    max_crop numeric(5,4) DEFAULT 0 NOT NULL,
    min_width integer,
    min_height integer,
    sharpen numeric(5,4) DEFAULT 0 NOT NULL,
    last_mod_time integer DEFAULT 0 NOT NULL
);

--
-- Name: piwigo_extension_ignored_updates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_extension_ignored_updates (
    extension_type character varying(16) NOT NULL,
    extension_id character varying(64) NOT NULL,
    ignored_at timestamp(0) without time zone NOT NULL
);

--
-- Name: piwigo_favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_favorites (
    user_id integer NOT NULL,
    image_id integer NOT NULL
);

--
-- Name: piwigo_group_access; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_group_access (
    group_id smallint NOT NULL,
    cat_id smallint NOT NULL
);

--
-- Name: piwigo_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_groups (
    id smallint NOT NULL,
    name character varying(255) NOT NULL,
    is_default character varying(8) NOT NULL,
    lastmodified timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);

--
-- Name: piwigo_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_history; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_history (
    id integer NOT NULL,
    date date NOT NULL,
    "time" time(0) without time zone NOT NULL,
    user_id integer NOT NULL,
    ip character varying(39) NOT NULL,
    section character varying(12) DEFAULT NULL::character varying,
    category_id smallint,
    search_id integer,
    tag_ids character varying(50) DEFAULT NULL::character varying,
    image_id integer,
    image_type character varying(8) DEFAULT NULL::character varying,
    format_id integer,
    auth_key_id integer,
    CONSTRAINT chk_history_category_id_unsigned CHECK (((category_id IS NULL) OR (category_id >= 0))),
    CONSTRAINT chk_history_image_id_unsigned CHECK (((image_id IS NULL) OR (image_id >= 0)))
);

--
-- Name: piwigo_history_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_history_summary; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_history_summary (
    year smallint NOT NULL,
    month smallint,
    day smallint,
    hour smallint,
    nb_pages integer,
    history_id_from integer,
    history_id_to integer
);

--
-- Name: piwigo_image_category; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_image_category (
    image_id integer NOT NULL,
    category_id smallint NOT NULL,
    rank integer
);

--
-- Name: piwigo_image_format; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_image_format (
    format_id integer NOT NULL,
    image_id integer NOT NULL,
    ext character varying(255) NOT NULL,
    filesize integer
);

--
-- Name: piwigo_image_format_format_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_image_format ALTER COLUMN format_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_image_format_format_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_image_tag; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_image_tag (
    image_id integer NOT NULL,
    tag_id smallint NOT NULL
);

--
-- Name: piwigo_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_images (
    id integer NOT NULL,
    file character varying(255) NOT NULL,
    date_available timestamp(0) without time zone NOT NULL,
    date_creation timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    name character varying(255) DEFAULT NULL::character varying,
    comment text,
    author character varying(255) DEFAULT NULL::character varying,
    hit integer NOT NULL,
    filesize integer,
    width smallint,
    height smallint,
    coi character varying(4) DEFAULT NULL::character varying,
    representative_ext character varying(4) DEFAULT NULL::character varying,
    date_metadata_update date,
    rating_score double precision,
    path character varying(255) NOT NULL,
    storage_category_id smallint,
    level smallint NOT NULL,
    md5sum character varying(32) DEFAULT NULL::character varying,
    added_by integer,
    rotation smallint,
    latitude double precision,
    longitude double precision,
    lastmodified timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);

--
-- Name: piwigo_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_integrity_ignored_anomalies; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_integrity_ignored_anomalies (
    anomaly_id character varying(64) NOT NULL,
    piwigo_version character varying(16) NOT NULL,
    ignored_at timestamp(0) without time zone NOT NULL
);

--
-- Name: piwigo_languages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_languages (
    id character varying(64) NOT NULL,
    version character varying(64) NOT NULL,
    name character varying(64) DEFAULT NULL::character varying
);

--
-- Name: piwigo_lounge; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_lounge (
    image_id integer NOT NULL,
    category_id smallint NOT NULL
);

--
-- Name: piwigo_old_permalinks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_old_permalinks (
    cat_id smallint NOT NULL,
    permalink character varying(64) NOT NULL,
    date_deleted timestamp(0) without time zone NOT NULL,
    last_hit timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    hit integer NOT NULL
);

--
-- Name: piwigo_plugin_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_plugin_migrations (
    plugin_id character varying(64) NOT NULL,
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone NOT NULL
);

--
-- Name: piwigo_plugins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_plugins (
    id character varying(64) NOT NULL,
    state character varying(8) NOT NULL,
    version character varying(64) NOT NULL
);

--
-- Name: piwigo_rate; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_rate (
    user_id integer NOT NULL,
    element_id integer NOT NULL,
    anonymous_id character varying(45) NOT NULL,
    rate smallint NOT NULL,
    date date NOT NULL
);

--
-- Name: piwigo_search; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_search (
    id integer NOT NULL,
    search_uuid character varying(23) DEFAULT NULL::character varying,
    created_on timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    created_by integer,
    forked_from integer,
    rules text
);

--
-- Name: piwigo_search_filter_view; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_search_filter_view (
    name character varying(64) NOT NULL,
    config_json json NOT NULL,
    created_at timestamp(0) without time zone NOT NULL
);

--
-- Name: piwigo_search_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_search ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_search_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_sessions (
    id character varying(50) NOT NULL,
    data text NOT NULL,
    expiration timestamp(0) without time zone NOT NULL
);

--
-- Name: piwigo_sites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_sites (
    id smallint NOT NULL,
    galleries_url character varying(255) NOT NULL
);

--
-- Name: piwigo_sites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_sites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_sites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_tags; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_tags (
    id smallint NOT NULL,
    name character varying(255) NOT NULL,
    url_name character varying(255) NOT NULL,
    lastmodified timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);

--
-- Name: piwigo_tags_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_tags ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_tags_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_themes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_themes (
    id character varying(64) NOT NULL,
    version character varying(64) NOT NULL,
    name character varying(64) DEFAULT NULL::character varying
);

--
-- Name: piwigo_upgrade; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_upgrade (
    id character varying(20) NOT NULL,
    applied timestamp(0) without time zone NOT NULL,
    description character varying(255) DEFAULT NULL::character varying
);

--
-- Name: piwigo_user_access; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_user_access (
    user_id integer NOT NULL,
    cat_id smallint NOT NULL
);

--
-- Name: piwigo_user_auth_keys; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_user_auth_keys (
    auth_key_id integer NOT NULL,
    auth_key character varying(255) NOT NULL,
    apikey_secret character varying(255) DEFAULT NULL::character varying,
    user_id integer NOT NULL,
    created_on timestamp(0) without time zone NOT NULL,
    duration integer,
    expired_on timestamp(0) without time zone NOT NULL,
    apikey_name character varying(100) DEFAULT NULL::character varying,
    key_type character varying(40) DEFAULT NULL::character varying,
    revoked_on timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    last_used_on timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    last_notified_on timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);

--
-- Name: piwigo_user_auth_keys_auth_key_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_user_auth_keys ALTER COLUMN auth_key_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_user_auth_keys_auth_key_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_user_cache; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_user_cache (
    user_id integer NOT NULL,
    need_update character varying(8) NOT NULL,
    cache_update_time integer NOT NULL,
    forbidden_categories text,
    nb_total_images integer,
    last_photo_date timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    nb_available_tags integer,
    nb_available_comments integer,
    image_access_type character varying(8) NOT NULL,
    image_access_list text
);

--
-- Name: piwigo_user_cache_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_user_cache_categories (
    user_id integer NOT NULL,
    cat_id smallint NOT NULL,
    date_last timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    max_date_last timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    nb_images integer NOT NULL,
    count_images integer,
    nb_categories integer,
    count_categories integer,
    user_representative_picture_id integer
);

--
-- Name: piwigo_user_failed_logins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_user_failed_logins (
    id integer NOT NULL,
    user_id integer,
    ip character varying(45) NOT NULL,
    attempted_at timestamp(0) without time zone NOT NULL
);

--
-- Name: piwigo_user_failed_logins_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_user_failed_logins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_user_failed_logins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_user_feed; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_user_feed (
    id character varying(50) NOT NULL,
    user_id integer NOT NULL,
    last_check timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);

--
-- Name: piwigo_user_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_user_group (
    user_id integer NOT NULL,
    group_id smallint NOT NULL
);

--
-- Name: piwigo_user_infos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_user_infos (
    user_id integer NOT NULL,
    nb_image_page smallint NOT NULL,
    status character varying(9) NOT NULL,
    language character varying(50) NOT NULL,
    expand character varying(8) NOT NULL,
    show_nb_comments character varying(8) NOT NULL,
    show_nb_hits character varying(8) NOT NULL,
    recent_period smallint NOT NULL,
    theme character varying(255) NOT NULL,
    registration_date timestamp(0) without time zone NOT NULL,
    enabled_high character varying(8) NOT NULL,
    level smallint NOT NULL,
    activation_key character varying(255) DEFAULT NULL::character varying,
    activation_key_expire timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    last_visit timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    last_visit_from_history character varying(8) NOT NULL,
    lastmodified timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    preferences text
);

--
-- Name: piwigo_user_mail_notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_user_mail_notification (
    user_id integer NOT NULL,
    check_key character varying(16) NOT NULL,
    enabled character varying(8) NOT NULL,
    last_send timestamp(0) without time zone DEFAULT NULL::timestamp without time zone
);

--
-- Name: piwigo_users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.piwigo_users (
    id integer NOT NULL,
    username character varying(100) NOT NULL,
    password character varying(255) DEFAULT NULL::character varying,
    mail_address character varying(255) DEFAULT NULL::character varying
);

--
-- Name: piwigo_users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.piwigo_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.piwigo_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: piwigo_activity piwigo_activity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_activity
    ADD CONSTRAINT piwigo_activity_pkey PRIMARY KEY (activity_id);

--
-- Name: piwigo_caddie piwigo_caddie_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_caddie
    ADD CONSTRAINT piwigo_caddie_pkey PRIMARY KEY (user_id, element_id);

--
-- Name: piwigo_categories piwigo_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_categories
    ADD CONSTRAINT piwigo_categories_pkey PRIMARY KEY (id);

--
-- Name: piwigo_comments piwigo_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_comments
    ADD CONSTRAINT piwigo_comments_pkey PRIMARY KEY (id);

--
-- Name: piwigo_config piwigo_config_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_config
    ADD CONSTRAINT piwigo_config_pkey PRIMARY KEY (param);

--
-- Name: piwigo_derivative_settings piwigo_derivative_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_derivative_settings
    ADD CONSTRAINT piwigo_derivative_settings_pkey PRIMARY KEY (id);

--
-- Name: piwigo_derivative_size piwigo_derivative_size_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_derivative_size
    ADD CONSTRAINT piwigo_derivative_size_pkey PRIMARY KEY (name);

--
-- Name: piwigo_extension_ignored_updates piwigo_extension_ignored_updates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_extension_ignored_updates
    ADD CONSTRAINT piwigo_extension_ignored_updates_pkey PRIMARY KEY (extension_type, extension_id);

--
-- Name: piwigo_favorites piwigo_favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_favorites
    ADD CONSTRAINT piwigo_favorites_pkey PRIMARY KEY (user_id, image_id);

--
-- Name: piwigo_group_access piwigo_group_access_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_group_access
    ADD CONSTRAINT piwigo_group_access_pkey PRIMARY KEY (group_id, cat_id);

--
-- Name: piwigo_groups piwigo_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_groups
    ADD CONSTRAINT piwigo_groups_pkey PRIMARY KEY (id);

--
-- Name: piwigo_history piwigo_history_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_history
    ADD CONSTRAINT piwigo_history_pkey PRIMARY KEY (id);

--
-- Name: piwigo_image_category piwigo_image_category_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_image_category
    ADD CONSTRAINT piwigo_image_category_pkey PRIMARY KEY (image_id, category_id);

--
-- Name: piwigo_image_format piwigo_image_format_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_image_format
    ADD CONSTRAINT piwigo_image_format_pkey PRIMARY KEY (format_id);

--
-- Name: piwigo_image_tag piwigo_image_tag_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_image_tag
    ADD CONSTRAINT piwigo_image_tag_pkey PRIMARY KEY (image_id, tag_id);

--
-- Name: piwigo_images piwigo_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_images
    ADD CONSTRAINT piwigo_images_pkey PRIMARY KEY (id);

--
-- Name: piwigo_integrity_ignored_anomalies piwigo_integrity_ignored_anomalies_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_integrity_ignored_anomalies
    ADD CONSTRAINT piwigo_integrity_ignored_anomalies_pkey PRIMARY KEY (anomaly_id, piwigo_version);

--
-- Name: piwigo_languages piwigo_languages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_languages
    ADD CONSTRAINT piwigo_languages_pkey PRIMARY KEY (id);

--
-- Name: piwigo_lounge piwigo_lounge_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_lounge
    ADD CONSTRAINT piwigo_lounge_pkey PRIMARY KEY (image_id, category_id);

--
-- Name: piwigo_old_permalinks piwigo_old_permalinks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_old_permalinks
    ADD CONSTRAINT piwigo_old_permalinks_pkey PRIMARY KEY (permalink);

--
-- Name: piwigo_plugin_migrations piwigo_plugin_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_plugin_migrations
    ADD CONSTRAINT piwigo_plugin_migrations_pkey PRIMARY KEY (plugin_id, version);

--
-- Name: piwigo_plugins piwigo_plugins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_plugins
    ADD CONSTRAINT piwigo_plugins_pkey PRIMARY KEY (id);

--
-- Name: piwigo_rate piwigo_rate_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_rate
    ADD CONSTRAINT piwigo_rate_pkey PRIMARY KEY (element_id, user_id, anonymous_id);

--
-- Name: piwigo_search_filter_view piwigo_search_filter_view_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_search_filter_view
    ADD CONSTRAINT piwigo_search_filter_view_pkey PRIMARY KEY (name);

--
-- Name: piwigo_search piwigo_search_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_search
    ADD CONSTRAINT piwigo_search_pkey PRIMARY KEY (id);

--
-- Name: piwigo_sessions piwigo_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_sessions
    ADD CONSTRAINT piwigo_sessions_pkey PRIMARY KEY (id);

--
-- Name: piwigo_sites piwigo_sites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_sites
    ADD CONSTRAINT piwigo_sites_pkey PRIMARY KEY (id);

--
-- Name: piwigo_tags piwigo_tags_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_tags
    ADD CONSTRAINT piwigo_tags_pkey PRIMARY KEY (id);

--
-- Name: piwigo_themes piwigo_themes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_themes
    ADD CONSTRAINT piwigo_themes_pkey PRIMARY KEY (id);

--
-- Name: piwigo_upgrade piwigo_upgrade_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_upgrade
    ADD CONSTRAINT piwigo_upgrade_pkey PRIMARY KEY (id);

--
-- Name: piwigo_user_access piwigo_user_access_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_access
    ADD CONSTRAINT piwigo_user_access_pkey PRIMARY KEY (user_id, cat_id);

--
-- Name: piwigo_user_auth_keys piwigo_user_auth_keys_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_auth_keys
    ADD CONSTRAINT piwigo_user_auth_keys_pkey PRIMARY KEY (auth_key_id);

--
-- Name: piwigo_user_cache_categories piwigo_user_cache_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_cache_categories
    ADD CONSTRAINT piwigo_user_cache_categories_pkey PRIMARY KEY (user_id, cat_id);

--
-- Name: piwigo_user_cache piwigo_user_cache_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_cache
    ADD CONSTRAINT piwigo_user_cache_pkey PRIMARY KEY (user_id);

--
-- Name: piwigo_user_failed_logins piwigo_user_failed_logins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_failed_logins
    ADD CONSTRAINT piwigo_user_failed_logins_pkey PRIMARY KEY (id);

--
-- Name: piwigo_user_feed piwigo_user_feed_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_feed
    ADD CONSTRAINT piwigo_user_feed_pkey PRIMARY KEY (id);

--
-- Name: piwigo_user_group piwigo_user_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_group
    ADD CONSTRAINT piwigo_user_group_pkey PRIMARY KEY (group_id, user_id);

--
-- Name: piwigo_user_infos piwigo_user_infos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_infos
    ADD CONSTRAINT piwigo_user_infos_pkey PRIMARY KEY (user_id);

--
-- Name: piwigo_user_mail_notification piwigo_user_mail_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_mail_notification
    ADD CONSTRAINT piwigo_user_mail_notification_pkey PRIMARY KEY (user_id);

--
-- Name: piwigo_users piwigo_users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_users
    ADD CONSTRAINT piwigo_users_pkey PRIMARY KEY (id);

--
-- Name: history_summary_ymdh; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX history_summary_ymdh ON public.piwigo_history_summary USING btree (year, month, day, hour);

--
-- Name: idx_1069aef21f1f2a24; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_1069aef21f1f2a24 ON public.piwigo_rate USING btree (element_id);

--
-- Name: idx_1069aef2a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_1069aef2a76ed395 ON public.piwigo_rate USING btree (user_id);

--
-- Name: idx_1bf6b975c828edac; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_1bf6b975c828edac ON public.piwigo_search USING btree (forked_from);

--
-- Name: idx_1bf6b975de12ab56; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_1bf6b975de12ab56 ON public.piwigo_search USING btree (created_by);

--
-- Name: idx_2c33ff4ca76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_2c33ff4ca76ed395 ON public.piwigo_user_access USING btree (user_id);

--
-- Name: idx_2c33ff4ce6ada943; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_2c33ff4ce6ada943 ON public.piwigo_user_access USING btree (cat_id);

--
-- Name: idx_3aecf09f3da5256d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_3aecf09f3da5256d ON public.piwigo_image_format USING btree (image_id);

--
-- Name: idx_468ba6e91f1f2a24; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_468ba6e91f1f2a24 ON public.piwigo_caddie USING btree (element_id);

--
-- Name: idx_468ba6e9a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_468ba6e9a76ed395 ON public.piwigo_caddie USING btree (user_id);

--
-- Name: idx_4f19dcb818d664c3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_4f19dcb818d664c3 ON public.piwigo_images USING btree (storage_category_id);

--
-- Name: idx_4f19dcb8699b6baf; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_4f19dcb8699b6baf ON public.piwigo_images USING btree (added_by);

--
-- Name: idx_4f2c9ec53da5256d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_4f2c9ec53da5256d ON public.piwigo_comments USING btree (image_id);

--
-- Name: idx_4f2c9ec5f675f31b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_4f2c9ec5f675f31b ON public.piwigo_comments USING btree (author_id);

--
-- Name: idx_4fc8c5d112469de2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_4fc8c5d112469de2 ON public.piwigo_history USING btree (category_id);

--
-- Name: idx_4fc8c5d12db7f2d1; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_4fc8c5d12db7f2d1 ON public.piwigo_history USING btree (auth_key_id);

--
-- Name: idx_4fc8c5d13da5256d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_4fc8c5d13da5256d ON public.piwigo_history USING btree (image_id);

--
-- Name: idx_4fc8c5d1650760a9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_4fc8c5d1650760a9 ON public.piwigo_history USING btree (search_id);

--
-- Name: idx_4fc8c5d1a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_4fc8c5d1a76ed395 ON public.piwigo_history USING btree (user_id);

--
-- Name: idx_4fc8c5d1d629f605; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_4fc8c5d1d629f605 ON public.piwigo_history USING btree (format_id);

--
-- Name: idx_583fc83ea76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_583fc83ea76ed395 ON public.piwigo_user_group USING btree (user_id);

--
-- Name: idx_583fc83efe54d947; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_583fc83efe54d947 ON public.piwigo_user_group USING btree (group_id);

--
-- Name: idx_69644583a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_69644583a76ed395 ON public.piwigo_user_feed USING btree (user_id);

--
-- Name: idx_6bc62a313da5256d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_6bc62a313da5256d ON public.piwigo_image_tag USING btree (image_id);

--
-- Name: idx_6bc62a31bad26311; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_6bc62a31bad26311 ON public.piwigo_image_tag USING btree (tag_id);

--
-- Name: idx_735c32ff12469de2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_735c32ff12469de2 ON public.piwigo_lounge USING btree (category_id);

--
-- Name: idx_735c32ff3da5256d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_735c32ff3da5256d ON public.piwigo_lounge USING btree (image_id);

--
-- Name: idx_9ea42f0ce6ada943; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_9ea42f0ce6ada943 ON public.piwigo_group_access USING btree (cat_id);

--
-- Name: idx_9ea42f0cfe54d947; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_9ea42f0cfe54d947 ON public.piwigo_group_access USING btree (group_id);

--
-- Name: idx_b27cbe76a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_b27cbe76a76ed395 ON public.piwigo_user_failed_logins USING btree (user_id);

--
-- Name: idx_bcc601b599eb8ea2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_bcc601b599eb8ea2 ON public.piwigo_activity USING btree (performed_by);

--
-- Name: idx_d4cc2d143da5256d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_d4cc2d143da5256d ON public.piwigo_favorites USING btree (image_id);

--
-- Name: idx_d4cc2d14a76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_d4cc2d14a76ed395 ON public.piwigo_favorites USING btree (user_id);

--
-- Name: idx_e677ee4ba76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_e677ee4ba76ed395 ON public.piwigo_user_auth_keys USING btree (user_id);

--
-- Name: idx_edce31cb9e69cec8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_edce31cb9e69cec8 ON public.piwigo_categories USING btree (representative_picture_id);

--
-- Name: idx_edce31cbc7f87b72; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_edce31cbc7f87b72 ON public.piwigo_categories USING btree (id_uppercat);

--
-- Name: idx_f3cc0bfba76ed395; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_f3cc0bfba76ed395 ON public.piwigo_user_cache_categories USING btree (user_id);

--
-- Name: idx_f3cc0bfbe6ada943; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_f3cc0bfbe6ada943 ON public.piwigo_user_cache_categories USING btree (cat_id);

--
-- Name: idx_f583509e12469de2; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_f583509e12469de2 ON public.piwigo_image_category USING btree (category_id);

--
-- Name: idx_f583509e3da5256d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_f583509e3da5256d ON public.piwigo_image_category USING btree (image_id);

--
-- Name: idx_history_date_desc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_history_date_desc ON public.piwigo_history USING btree (date DESC, id DESC);

--
-- Name: idx_images_date_desc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_images_date_desc ON public.piwigo_images USING btree (date_available DESC, id DESC);

--
-- Name: idx_user_failed_logins_ip_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_failed_logins_ip_time ON public.piwigo_user_failed_logins USING btree (ip, attempted_at);

--
-- Name: idx_user_failed_logins_user_time; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_failed_logins_user_time ON public.piwigo_user_failed_logins USING btree (user_id, attempted_at);

--
-- Name: piwigo_activity fk_activity_performed_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_activity
    ADD CONSTRAINT fk_activity_performed_by FOREIGN KEY (performed_by) REFERENCES public.piwigo_users(id) ON DELETE SET NULL;

--
-- Name: piwigo_caddie fk_caddie_element_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_caddie
    ADD CONSTRAINT fk_caddie_element_id FOREIGN KEY (element_id) REFERENCES public.piwigo_images(id) ON DELETE CASCADE;

--
-- Name: piwigo_caddie fk_caddie_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_caddie
    ADD CONSTRAINT fk_caddie_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- Name: piwigo_categories fk_categories_id_uppercat; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_categories
    ADD CONSTRAINT fk_categories_id_uppercat FOREIGN KEY (id_uppercat) REFERENCES public.piwigo_categories(id) ON DELETE SET NULL;

--
-- Name: piwigo_categories fk_categories_representative_picture_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_categories
    ADD CONSTRAINT fk_categories_representative_picture_id FOREIGN KEY (representative_picture_id) REFERENCES public.piwigo_images(id) ON DELETE SET NULL;

--
-- Name: piwigo_comments fk_comments_author_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_comments
    ADD CONSTRAINT fk_comments_author_id FOREIGN KEY (author_id) REFERENCES public.piwigo_users(id) ON DELETE SET NULL;

--
-- Name: piwigo_comments fk_comments_image_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_comments
    ADD CONSTRAINT fk_comments_image_id FOREIGN KEY (image_id) REFERENCES public.piwigo_images(id) ON DELETE CASCADE;

--
-- Name: piwigo_favorites fk_favorites_image_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_favorites
    ADD CONSTRAINT fk_favorites_image_id FOREIGN KEY (image_id) REFERENCES public.piwigo_images(id) ON DELETE CASCADE;

--
-- Name: piwigo_favorites fk_favorites_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_favorites
    ADD CONSTRAINT fk_favorites_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- Name: piwigo_group_access fk_group_access_cat_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_group_access
    ADD CONSTRAINT fk_group_access_cat_id FOREIGN KEY (cat_id) REFERENCES public.piwigo_categories(id) ON DELETE CASCADE;

--
-- Name: piwigo_group_access fk_group_access_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_group_access
    ADD CONSTRAINT fk_group_access_group_id FOREIGN KEY (group_id) REFERENCES public.piwigo_groups(id) ON DELETE CASCADE;

--
-- Name: piwigo_history fk_history_auth_key_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_history
    ADD CONSTRAINT fk_history_auth_key_id FOREIGN KEY (auth_key_id) REFERENCES public.piwigo_user_auth_keys(auth_key_id) ON DELETE SET NULL;

--
-- Name: piwigo_history fk_history_category_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_history
    ADD CONSTRAINT fk_history_category_id FOREIGN KEY (category_id) REFERENCES public.piwigo_categories(id) ON DELETE SET NULL;

--
-- Name: piwigo_history fk_history_format_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_history
    ADD CONSTRAINT fk_history_format_id FOREIGN KEY (format_id) REFERENCES public.piwigo_image_format(format_id) ON DELETE SET NULL;

--
-- Name: piwigo_history fk_history_image_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_history
    ADD CONSTRAINT fk_history_image_id FOREIGN KEY (image_id) REFERENCES public.piwigo_images(id) ON DELETE SET NULL;

--
-- Name: piwigo_history fk_history_search_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_history
    ADD CONSTRAINT fk_history_search_id FOREIGN KEY (search_id) REFERENCES public.piwigo_search(id) ON DELETE SET NULL;

--
-- Name: piwigo_history fk_history_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_history
    ADD CONSTRAINT fk_history_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- Name: piwigo_image_category fk_image_category_category_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_image_category
    ADD CONSTRAINT fk_image_category_category_id FOREIGN KEY (category_id) REFERENCES public.piwigo_categories(id) ON DELETE CASCADE;

--
-- Name: piwigo_image_category fk_image_category_image_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_image_category
    ADD CONSTRAINT fk_image_category_image_id FOREIGN KEY (image_id) REFERENCES public.piwigo_images(id) ON DELETE CASCADE;

--
-- Name: piwigo_image_format fk_image_format_image_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_image_format
    ADD CONSTRAINT fk_image_format_image_id FOREIGN KEY (image_id) REFERENCES public.piwigo_images(id) ON DELETE CASCADE;

--
-- Name: piwigo_image_tag fk_image_tag_image_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_image_tag
    ADD CONSTRAINT fk_image_tag_image_id FOREIGN KEY (image_id) REFERENCES public.piwigo_images(id) ON DELETE CASCADE;

--
-- Name: piwigo_image_tag fk_image_tag_tag_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_image_tag
    ADD CONSTRAINT fk_image_tag_tag_id FOREIGN KEY (tag_id) REFERENCES public.piwigo_tags(id) ON DELETE CASCADE;

--
-- Name: piwigo_images fk_images_added_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_images
    ADD CONSTRAINT fk_images_added_by FOREIGN KEY (added_by) REFERENCES public.piwigo_users(id) ON DELETE SET NULL;

--
-- Name: piwigo_images fk_images_storage_category_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_images
    ADD CONSTRAINT fk_images_storage_category_id FOREIGN KEY (storage_category_id) REFERENCES public.piwigo_categories(id) ON DELETE SET NULL;

--
-- Name: piwigo_lounge fk_lounge_category_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_lounge
    ADD CONSTRAINT fk_lounge_category_id FOREIGN KEY (category_id) REFERENCES public.piwigo_categories(id) ON DELETE CASCADE;

--
-- Name: piwigo_lounge fk_lounge_image_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_lounge
    ADD CONSTRAINT fk_lounge_image_id FOREIGN KEY (image_id) REFERENCES public.piwigo_images(id) ON DELETE CASCADE;

--
-- Name: piwigo_rate fk_rate_element_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_rate
    ADD CONSTRAINT fk_rate_element_id FOREIGN KEY (element_id) REFERENCES public.piwigo_images(id) ON DELETE CASCADE;

--
-- Name: piwigo_rate fk_rate_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_rate
    ADD CONSTRAINT fk_rate_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- Name: piwigo_search fk_search_created_by; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_search
    ADD CONSTRAINT fk_search_created_by FOREIGN KEY (created_by) REFERENCES public.piwigo_users(id) ON DELETE SET NULL;

--
-- Name: piwigo_search fk_search_forked_from; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_search
    ADD CONSTRAINT fk_search_forked_from FOREIGN KEY (forked_from) REFERENCES public.piwigo_search(id) ON DELETE SET NULL;

--
-- Name: piwigo_user_access fk_user_access_cat_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_access
    ADD CONSTRAINT fk_user_access_cat_id FOREIGN KEY (cat_id) REFERENCES public.piwigo_categories(id) ON DELETE CASCADE;

--
-- Name: piwigo_user_access fk_user_access_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_access
    ADD CONSTRAINT fk_user_access_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- Name: piwigo_user_auth_keys fk_user_auth_keys_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_auth_keys
    ADD CONSTRAINT fk_user_auth_keys_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- Name: piwigo_user_cache_categories fk_user_cache_categories_cat_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_cache_categories
    ADD CONSTRAINT fk_user_cache_categories_cat_id FOREIGN KEY (cat_id) REFERENCES public.piwigo_categories(id) ON DELETE CASCADE;

--
-- Name: piwigo_user_cache_categories fk_user_cache_categories_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_cache_categories
    ADD CONSTRAINT fk_user_cache_categories_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- Name: piwigo_user_cache fk_user_cache_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_cache
    ADD CONSTRAINT fk_user_cache_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- Name: piwigo_user_failed_logins fk_user_failed_logins_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_failed_logins
    ADD CONSTRAINT fk_user_failed_logins_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- Name: piwigo_user_feed fk_user_feed_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_feed
    ADD CONSTRAINT fk_user_feed_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- Name: piwigo_user_group fk_user_group_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_group
    ADD CONSTRAINT fk_user_group_group_id FOREIGN KEY (group_id) REFERENCES public.piwigo_groups(id) ON DELETE CASCADE;

--
-- Name: piwigo_user_group fk_user_group_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_group
    ADD CONSTRAINT fk_user_group_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- Name: piwigo_user_infos fk_user_infos_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_infos
    ADD CONSTRAINT fk_user_infos_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- Name: piwigo_user_mail_notification fk_user_mail_notification_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.piwigo_user_mail_notification
    ADD CONSTRAINT fk_user_mail_notification_user_id FOREIGN KEY (user_id) REFERENCES public.piwigo_users(id) ON DELETE CASCADE;

--
-- PostgreSQL database dump complete
--

\unrestrict R07nQK1U9NwWmxgEEuQwObQUO53RVlPhRQEJtRzetl51ciiFikVG9IT8HZjWu2N
