<?php

declare(strict_types=1);

use PHPUnit\Framework\Assert;
use Piwigo\Tools\PhpStan\Latte\GeneratedFileErrorMapper;

beforeEach(function (): void {
    $this->dir = sys_get_temp_dir() . '/piwigo-error-mapper-test-' . bin2hex(random_bytes(8));
    mkdir($this->dir, 0o777, true);
    $this->mapper = new GeneratedFileErrorMapper($this->dir);
});

afterEach(function (): void {
    exec('rm -rf ' . escapeshellarg($this->dir));
});

function error_mapper_test_write(string $dir, string $content): string
{
    $path = $dir . '/themes-default-template-page.latte.php';
    file_put_contents($path, $content);

    return $path;
}

it('maps a reported line to the nearest preceding pos marker in the real template', function (): void {
    $path = error_mapper_test_write($this->dir, <<<'PHP'
        <?php declare(strict_types=1);

        /** Generated by Latte 3.1.6 */

        /** source: /repo/themes/default/template/page.latte */
        final class Template_abc extends Latte\Runtime\Template
        {
            public function main(array $ʟ_args): void
            {
                extract($ʟ_args);
                /** @var string $FOO */
                echo Shims::translate($FOO) /* pos 7:14 */;
                echo strtoupper($FOO);
                echo 'x' /* pos 9:2 */;
            }
        }
        PHP);

    // Line 13 (the strtoupper echo, no pos comment of its own) walks back
    // to line 12's marker.
    expect($this->mapper->map($path, 13))
        ->toBe([
            'file' => '/repo/themes/default/template/page.latte',
            'line' => 7,
            'column' => 14,
        ]);
    // Line 14 has its own marker.
    expect($this->mapper->map($path, 14))
        ->toBe([
            'file' => '/repo/themes/default/template/page.latte',
            'line' => 9,
            'column' => 2,
        ]);
});

it('maps to the source file with no line when the error precedes every pos marker', function (): void {
    $path = error_mapper_test_write($this->dir, <<<'PHP'
        <?php declare(strict_types=1);
        /** source: /repo/themes/default/template/page.latte */
        final class Template_abc
        {
            public function main(): void
            {
                echo 'x' /* pos 3:1 */;
            }
        }
        PHP);

    expect($this->mapper->map($path, 3))
        ->toBe([
            'file' => '/repo/themes/default/template/page.latte',
            'line' => null,
            'column' => null,
        ]);
    expect($this->mapper->map($path, null))
        ->toBe([
            'file' => '/repo/themes/default/template/page.latte',
            'line' => null,
            'column' => null,
        ]);
});

it('never maps files outside the analysis directory or without a source header', function (): void {
    expect($this->mapper->map('/somewhere/else/file.php', 10))
        ->toBeNull();
    expect($this->mapper->isGeneratedFile('/somewhere/else/file.php'))
        ->toBeFalse();

    $noHeader = error_mapper_test_write($this->dir, "<?php\necho 'no source header';\n");
    expect($this->mapper->map($noHeader, 2))
        ->toBeNull();
});

it('maps a real generated file from the live analysis directory', function (): void {
    $repoRoot = dirname(__DIR__, 3);
    $liveDir = $repoRoot . '/_analysis/phpstan-latte';
    $liveFile = $liveDir . '/themes-admin-default-template-stats.latte.php';
    if (! is_file($liveFile)) {
        Assert::markTestSkipped('run bin/piwigo phpstan-latte:compile first');
    }

    $mapper = new GeneratedFileErrorMapper($liveDir);
    $lines = explode("\n", (string) file_get_contents($liveFile));
    $posLine = null;
    foreach ($lines as $i => $line) {
        if (str_contains($line, '/* pos ')) {
            $posLine = $i + 1;
            break;
        }
    }
    expect($posLine)
        ->not->toBeNull();

    $mapped = $mapper->map($liveFile, $posLine);
    expect($mapped)
        ->not->toBeNull();
    assert($mapped !== null);
    expect($mapped['file'])->toBe($repoRoot . '/themes/admin/default/template/stats.latte')
        ->and($mapped['line'])->toBeGreaterThan(0);
});
