<?php

declare(strict_types=1);

use Piwigo\Tools\PhpStan\Latte\VarTypeSyncer;

beforeEach(function (): void {
    $this->syncer = new VarTypeSyncer();
});

it('inserts a new block at the top of a file with no existing block', function (): void {
    // Insertion order, not re-sorted -- VariableMap::forTemplate() already
    // ksort()s before a real caller ever reaches this method.
    $result = $this->syncer->sync(
        "<div>{\$current}</div>\n",
        [
            'count' => '?int',
            'current' => '\\Piwigo\\Foo\\Bar',
        ],
        'ignored.latte',
    );

    expect($result->changed)
        ->toBeTrue();
    expect($result->content)
        ->toBe(
            "{* BEGIN varType (auto-generated by `composer lint:vartype:fix` -- do not hand-edit) *}\n"
                . "{varType ?int \$count}\n"
                . "{varType \\Piwigo\\Foo\\Bar \$current}\n"
                . "{* END varType *}\n"
                . "<div>{\$current}</div>\n",
        );
    expect($result->notices)
        ->toBe([]);
});

it('replaces an existing block in place, leaving surrounding content untouched', function (): void {
    $source = "{* BEGIN varType (auto-generated by `composer lint:vartype:fix` -- do not hand-edit) *}\n"
        . "{varType string \$stale}\n"
        . "{* END varType *}\n"
        . "<div>{\$current}</div>\n";

    $result = $this->syncer->sync($source, [
        'current' => '\\Piwigo\\Foo\\Bar',
    ], 'ignored.latte');

    expect($result->changed)
        ->toBeTrue();
    expect($result->content)
        ->toBe(
            "{* BEGIN varType (auto-generated by `composer lint:vartype:fix` -- do not hand-edit) *}\n"
                . "{varType \\Piwigo\\Foo\\Bar \$current}\n"
                . "{* END varType *}\n"
                . "<div>{\$current}</div>\n",
        );
});

it('removes an existing block entirely when there are no vars left', function (): void {
    $source = "{* BEGIN varType (auto-generated by `composer lint:vartype:fix` -- do not hand-edit) *}\n"
        . "{varType string \$stale}\n"
        . "{* END varType *}\n"
        . "<div>static</div>\n";

    $result = $this->syncer->sync($source, [], 'ignored.latte');

    expect($result->changed)
        ->toBeTrue();
    expect($result->content)
        ->toBe("<div>static</div>\n");
});

it('is a no-op when the file already has an up-to-date block', function (): void {
    $first = $this->syncer->sync("<div></div>\n", [
        'x' => 'string',
    ], 'ignored.latte');
    $second = $this->syncer->sync($first->content, [
        'x' => 'string',
    ], 'ignored.latte');

    expect($second->changed)
        ->toBeFalse();
    expect($second->content)
        ->toBe($first->content);
});

it('is a no-op when there were no vars and no block to begin with', function (): void {
    $result = $this->syncer->sync("<div></div>\n", [], 'ignored.latte');

    expect($result->changed)
        ->toBeFalse();
    expect($result->content)
        ->toBe("<div></div>\n");
});

it('skips invalid PHP identifiers with a notice instead of emitting a broken tag', function (): void {
    $result = $this->syncer->sync(
        "<div></div>\n",
        [
            'valid_name' => 'string',
            'invalid-name' => 'string',
        ],
        'themes/default/template/example.latte',
    );

    expect($result->content)
        ->toContain('{varType string $valid_name}')
        ->not->toContain('invalid-name');
    expect($result->notices)
        ->toHaveCount(1);
    expect($result->notices[0])->toContain("'invalid-name'")
        ->toContain('themes/default/template/example.latte');
});
