<?php

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    http_response_code(403);
    exit('This script can only be run from the command line.');
}

// A) requirements
//
// curl -s http://getcomposer.org/installer | php
// php composer.phar require knplabs/github-api php-http/guzzle6-adapter
//
// B) usage
//
// php gh.php --milestone=2.8.4 --html

$opt = getopt('', ['milestone:', 'html']);

if (! isset($opt['milestone']) || ! is_string($opt['milestone'])) {
    die('missing --milestone' . "\n");
}
$opt_milestone = $opt['milestone'];

// This file is generated by Composer
require_once 'vendor/autoload.php';

$client = new \Github\Client();
$milestones = $client->api('issue')
    ->milestones()
    ->all('Piwigo', 'Piwigo');

$milestone_number = null;

foreach ($milestones as $milestone) {
    if ($milestone['title'] == $opt_milestone) {
        $milestone_number = $milestone['number'];
    }
}

if ($milestone_number === null) {
    die('milestone ' . $opt_milestone . ' not found');
}

$issues = $client->api('issue')
    ->all('Piwigo', 'Piwigo', [
        'milestone' => $milestone_number,
        'state' => 'closed',
    ]);

foreach ($issues as $issue) {
    if (isset($opt['html'])) {
        echo '<li><a href="' . $issue['html_url'] . '">#' . $issue['number'] . '</a>: ' . $issue['title'] . '</li>' . "\n";
    } else {
        echo '#' . $issue['number'] . ' ' . $issue['title'] . "\n";
    }
}
