<?php

declare(strict_types=1);

/**
 * PHPStan type aliases for the Piwigo global $conf array.
 *
 * This file is a no-op include used only for its docblocks.
 * Add it to phpstan.neon bootstrapFiles when tightening $conf access.
 *
 * @phpstan-type Conf array{
 *     upload_dir: string, data_location: string, themes_dir: string,
 *     log_dir: string, ext_imagick_dir: string, ffmpeg_dir: string,
 *     no_photo_yet_url: string,
 *     dblayer: string, db_host: string, db_user: string, db_password: string,
 *     db_base: string, users_table: string|null,
 *     user_fields: array{id: string, username: string, password: string, email: string},
 *     apache_authentication: bool, external_authentification: bool,
 *     password_hash: callable-string, password_verify: callable-string,
 *     guest_id: int, default_user_id: int, insensitive_case_logon: bool,
 *     browser_language: bool, guest_access: bool,
 *     password_reset_duration: int, password_activation_duration: int,
 *     password_reset_code_duration: int,
 *     send_bcc_mail_webmaster: bool, mail_sender_name: string,
 *     mail_sender_email: string, mail_allow_html: bool,
 *     smtp_host: string, smtp_user: string, smtp_password: string,
 *     smtp_secure: 'ssl'|'tls'|null,
 *     picture_ext: list<string>, file_ext: list<string>, enable_formats: bool,
 *     format_ext: list<string>,
 *     graphics_library: 'auto'|'imagick'|'ext_imagick'|'gd',
 *     uniqueness_mode: 'md5sum'|'filename',
 *     tiff_representative_ext: 'png'|'jpg', chmod_value: int,
 *     derivative_default_size: 'small'|'medium'|'large',
 *     derivative_url_style: 0|1|2, derivatives_strip_metadata_threshold: int,
 *     animated_webp_compression_quality: int, max_requests: int,
 *     original_url_protection: ''|'images'|'all',
 *     upload_form_automatic_rotation: bool, upload_form_all_types: bool,
 *     upload_form_chunk_size: int, upload_form_max_file_size: int,
 *     enable_synchronization: bool, sync_chars_regex: string,
 *     sync_exclude_folders: list<string>, inheritance_by_default: bool,
 *     checksum_compute_blocksize: int, lounge_activate_threshold: int,
 *     lounge_max_duration: int,
 *     batch_manager_images_per_page_global: int,
 *     batch_manager_images_per_page_unit: int,
 *     show_queries: bool, show_gt: bool, debug_l10n: bool,
 *     debug_template: bool, debug_mail: bool, die_on_sql_error: bool,
 *     compiled_template_cache_language: bool, template_compile_check: bool,
 *     template_force_compile: bool, template_combine_files: bool,
 *     show_php_errors: int|string, show_php_errors_on_frontend: bool,
 *     session_use_cookies: bool, session_use_only_cookies: bool,
 *     session_use_trans_sid: bool, session_name: string,
 *     session_save_handler: 'db'|'file', authorize_remembering: bool,
 *     remember_me_name: string, remember_me_length: int,
 *     session_length: int, session_use_ip_address: bool,
 *     session_gc_probability: int,
 *     api_key_duration: list<string>, api_key_forbidden_methods: list<string>,
 *     auth_key_duration: int,
 *     nbm_default_value_user_enabled: bool,
 *     nbm_list_all_enabled_users_to_send: bool,
 *     nbm_max_treatment_timeout_percent: float,
 *     nbm_treatment_timeout_default: int,
 *     recent_post_dates: array{RSS: array{max_dates:int,max_elements:int,max_cats:int}, NBM: array{max_dates:int,max_elements:int,max_cats:int}},
 *     rss_feed_author: string,
 *     full_tag_cloud_items_number: int,
 *     menubar_tag_cloud_items_number: int,
 *     menubar_tag_cloud_content: 'always_all'|'current_only'|'all_or_current',
 *     content_tag_cloud_items_number: int, tags_levels: int,
 *     tags_default_display_mode: 'letters'|'cloud',
 *     tag_letters_column_number: int,
 *     related_albums_maximum_items_to_compute: int,
 *     related_albums_display_limit: int,
 *     quick_search_include_sub_albums: bool,
 *     default_filters_views: array<string, array{access: string, default: bool}|bool>,
 *     gallery_url: string|null,
 *     category_url_style: 'id'|'id-name',
 *     picture_url_style: 'id'|'id-file'|'file',
 *     tag_url_style: 'id'|'id-tag'|'tag',
 *     url_port: 'none'|'auto'|int,
 *     alternative_pem_url: string, pem_plugins_category: int,
 *     pem_themes_category: int, pem_languages_category: int,
 *     top_number: int, 'anti-flood_time': int, comment_spam_reject: bool,
 *     comment_spam_max_links: int, calendar_datefield: string,
 *     calendar_show_any: bool, calendar_show_empty: bool,
 *     newcat_default_commentable: bool, newcat_default_visible: bool,
 *     newcat_default_status: 'public'|'private',
 *     newcat_default_position: 'first'|'last',
 *     light_album_manager_threshold: int, level_separator: string,
 *     paginate_pages_around: int, show_version: bool, meta_ref: bool,
 *     links: array<string, string|array{label: string, new_window?: bool, nw_name?: string, nw_features?: string, eval_visible?: string}>,
 *     random_index_redirect: array<string, string>,
 *     header_notes: list<string>,
 *     show_thumbnail_caption: bool,
 *     allow_random_representative: bool,
 *     representative_cache_on_level: bool,
 *     representative_cache_on_subcats: bool,
 *     allow_html_descriptions: bool,
 *     available_permission_levels: list<int>,
 *     check_upgrade_feed: bool,
 *     rate_items: list<int>,
 *     default_redirect_method: 'http'|'html',
 *     double_password_type_in_admin: bool,
 *     comments_page_nb_comments: int|'all',
 *     update_notify_check_period: int,
 *     update_notify_reminder_period: int,
 *     send_piwigo_infos: bool,
 *     album_description_on_all_pages: bool,
 *     stat_compare_year_displayed: int,
 *     linked_album_search_limit: int,
 *     fs_quick_check_period: int,
 *     pdf_viewer_filesize_threshold: int,
 *     show_iptc: bool, show_iptc_mapping: array<string, string>,
 *     use_iptc: bool, use_iptc_mapping: array<string, string>,
 *     show_exif: bool, show_exif_fields: list<string>,
 *     use_exif: bool, use_exif_mapping: array<string, string>,
 *     allow_html_in_metadata: bool,
 *     metadata_keyword_separator_regex: string,
 *     nb_logs_page: int,
 *     history_autopurge_every: int,
 *     history_autopurge_keep_lines: int,
 *     history_autopurge_blocksize: int,
 *     log_level: 'OFF'|'CRITICAL'|'ERROR'|'WARNING'|'NOTICE'|'INFO'|'DEBUG',
 *     log_archive_days: int,
 *     use_proxy: bool, proxy_server: string, proxy_auth: string,
 *     slideshow_period_min: int, slideshow_period_max: int,
 *     slideshow_period_step: int, slideshow_period: int,
 *     slideshow_repeat: bool, light_slideshow: bool,
 *     admin_theme: string, enable_plugins: bool,
 *     allow_web_services: bool,
 *     ws_max_images_per_page: int, ws_max_users_per_page: int,
 *     show_newsletter_subscription: bool, show_piwigo_latest_news: bool,
 *     dashboard_check_for_updates: bool, dashboard_activity_nb_weeks: int,
 *     activity_display_connections: 'all'|'admins_only'|'none',
 *     album_move_delay_before_auto_opening: int,
 *     show_template_in_side_menu: bool,
 *     add_cache_to_storage_chart: bool,
 *     filter_pages: array<string, array{used?: bool, cancel?: bool, add_notes?: bool}>,
 *     webmaster_id?: int,
 *     secret_key?: string,
 *     piwigo_db_version?: string,
 *     piwigo_installed_version?: string,
 *     last_major_update?: string,
 *     order_by?: string,
 *     order_by_inside_category?: string,
 *     order_by_custom?: string,
 *     order_by_inside_category_custom?: string,
 *     extents_for_templates?: string,
 *     no_photo_yet?: bool,
 *     gallery_locked?: bool,
 *     mobile_theme?: string,
 *     plugin?: array<string, mixed>
 * }
 */
function phpstan_conf_alias_placeholder(): never
{
    throw new \LogicException('This function exists only for PHPStan type alias extraction.');
}
