#!/bin/bash

# Reimports the committed tests/Fixtures/piwigo-17.0.sql into the local test DB
# and waits for it to settle before returning. Used as a preceding step for
# composer test:browser/test:visual so those suites are self-contained and
# never depend on whatever state a previous manual run happened to leave the
# DB in (VR in particular produces a wave of false diffs if a CRUD-mutating
# test:browser run happened first without a reimport in between).
#
# Also clears the named cache pools' filesystem backing (_data/cache/piwigo.*,
# see src/Piwigo/Cache/CacheFactory.php) -- P23 batch 4b found live that a
# 300s-TTL CategoryTreeCache entry warmed by an earlier test:browser run
# survives a plain DB reimport (this script only ever touched the DB), so a
# later test:visual run can read a category tree that no longer matches the
# freshly-reimported fixture, producing a real (not flaky) VR mismatch on any
# page whose content depends on a named pool. Some subdirectories can be
# www-data-owned from live Apache-driven testing (directory write permission,
# not file ownership, governs deletion) -- sudo, matching this project's own
# established fix for the same class of permission gap elsewhere.
#
# Also clears _data/combined/ (FileCombiner's own combined CSS/JS bundle
# cache, see src/Piwigo/Template/FileCombiner.php) for the identical
# ownership-mismatch reason: a bundle file created directly by a torres-run
# CLI script (mode 644, owner torres) can never be regenerated by the
# www-data Apache worker afterward -- file_put_contents() then fails with a
# silent "Permission denied" warning on every request needing that bundle,
# confirmed live via _data/logs/test_errors.log.
#
# Also clears _data/i/ (cached derivative thumbnails) and regenerates the 5
# core fixture photos' own physical JPEG bytes via
# tools/regenerate-fixture-photos.php -- unlike every table above, upload/
# is gitignored, so a plain SQL reimport leaves whatever file a *previous*
# manual run happened to write at each row's own `path` untouched. Found
# live: VisualRegressionTest's committed .snap baselines silently drifted
# out of sync with the real, current FixturePhotoGenerator content because
# nothing ever refreshed upload/'s own bytes to match. Regenerating them
# here, deterministically, on every reimport closes that gap the same way
# the cache-pool/combined-bundle clears above already do for their own
# stale-state class.
#
# Reads DB credentials from .env.test, same variables IntegrationTestCase.php
# uses (PIWIGO_DB_HOST/USER/PASSWORD/BASE/PREFIX) — no PIWIGO_DB_PORT support,
# matching that class, which doesn't read one either.
#
# `piwigo_sites` id=1's own `galleries_url` is committed in the fixture as
# an absolute filesystem path (Piwigo\Core\Paths::$root . 'galleries/',
# matching exactly what Admin\Install\InstallWizard seeds it with on a real
# install) -- inherently tied to wherever *that* install's checkout lived,
# not portable data. Every checkout of this repo lives at a different path,
# so this is corrected here, at fixture-load time, the same way PIWIGO_TEST_NOW
# is environment-injected rather than baked into the fixture -- not a
# one-off patch. IntegrationTestCase::loadFixture() applies the identical
# correction for its own separate (non-shell-script) import path, since
# PHPUnit's Integration/Contract suites never invoke this script.

set -euo pipefail

set -a
source .env.test
set +a

mysql_args=(-h"${PIWIGO_DB_HOST}" -u"${PIWIGO_DB_USER}")
if [ -n "${PIWIGO_DB_PASSWORD:-}" ]; then
  mysql_args+=(-p"${PIWIGO_DB_PASSWORD}")
fi

mysql "${mysql_args[@]}" "${PIWIGO_DB_BASE}" < tests/Fixtures/piwigo-17.0.sql

until mysql "${mysql_args[@]}" "${PIWIGO_DB_BASE}" -e "SELECT COUNT(*) FROM ${PIWIGO_DB_PREFIX}images;" > /dev/null 2>&1; do
  sleep 0.5
done

# tests/Fixtures/piwigo-17.0.sql ships an entirely empty `themes` table (no
# INSERT rows at all) -- ThemeCatalog::getPwgThemes() reads this table
# directly, so ANY profile-save submission (ProfileController's own form, or
# ConfigurationSubController's "default" tab, both funnel through the same
# ProfileFormHandler::saveFromPost()) hits its `in_array($post['theme'],
# array_keys(getPwgThemes()), true)` guard against an empty haystack and
# 500s with "[Hacking attempt] incorrect theme value" -- confirmed live,
# independently, from two separate Browser test files. Seeded here (once,
# for the whole suite) rather than per-test, now that a second file hit the
# same wall.
mysql "${mysql_args[@]}" "${PIWIGO_DB_BASE}" -e "INSERT INTO ${PIWIGO_DB_PREFIX}themes (id, version, name) VALUES ('default', '1.0.0', 'Default') ON DUPLICATE KEY UPDATE name = 'Default';"

# This script always runs from the project root (composer.json's own
# `test:browser`/`test:visual` scripts invoke it as `bash tools/reimport-fixture.sh`
# from there) -- $(pwd)/ is this checkout's real Paths::$root value.
real_root="$(pwd)/"
mysql "${mysql_args[@]}" "${PIWIGO_DB_BASE}" -e "UPDATE ${PIWIGO_DB_PREFIX}sites SET galleries_url = '${real_root}galleries/' WHERE id = 1;"

sudo rm -rf _data/cache/piwigo.*/
sudo rm -rf _data/combined/*
sudo rm -rf _data/i/*

php tools/regenerate-fixture-photos.php
