#!/bin/bash

# Reimports the committed tests/Fixtures/piwigo-17.0.sql into the local test DB
# and waits for it to settle before returning. Used as a preceding step for
# composer test:browser/test:visual so those suites are self-contained and
# never depend on whatever state a previous manual run happened to leave the
# DB in (VR in particular produces a wave of false diffs if a CRUD-mutating
# test:browser run happened first without a reimport in between).
#
# Also clears the named cache pools' filesystem backing (_data/cache/piwigo.*,
# see src/Piwigo/Cache/CacheFactory.php) -- P23 batch 4b found live that a
# 300s-TTL CategoryTreeCache entry warmed by an earlier test:browser run
# survives a plain DB reimport (this script only ever touched the DB), so a
# later test:visual run can read a category tree that no longer matches the
# freshly-reimported fixture, producing a real (not flaky) VR mismatch on any
# page whose content depends on a named pool. Some subdirectories can be
# www-data-owned from live Apache-driven testing (directory write permission,
# not file ownership, governs deletion) -- sudo, matching this project's own
# established fix for the same class of permission gap elsewhere.
#
# Also clears _data/combined/ (FileCombiner's own combined CSS/JS bundle
# cache, see src/Piwigo/Template/FileCombiner.php) for the identical
# ownership-mismatch reason: a bundle file created directly by a torres-run
# CLI script (mode 644, owner torres) can never be regenerated by the
# www-data Apache worker afterward -- file_put_contents() then fails with a
# silent "Permission denied" warning on every request needing that bundle,
# confirmed live via _data/logs/test_errors.log.
#
# Also clears _data/i/ (cached derivative thumbnails) and regenerates the 5
# core fixture photos' own physical JPEG bytes via
# tools/regenerate-fixture-photos.php -- unlike every table above, upload/
# is gitignored, so a plain SQL reimport leaves whatever file a *previous*
# manual run happened to write at each row's own `path` untouched. Found
# live: VisualRegressionTest's committed .snap baselines silently drifted
# out of sync with the real, current FixturePhotoGenerator content because
# nothing ever refreshed upload/'s own bytes to match. Regenerating them
# here, deterministically, on every reimport closes that gap the same way
# the cache-pool/combined-bundle clears above already do for their own
# stale-state class.
#
# Reads DB credentials from .env.test, same variables IntegrationTestCase.php
# uses (PIWIGO_DB_HOST/USER/PASSWORD/BASE) — no PIWIGO_DB_PORT support,
# matching that class, which doesn't read one either.
#
# pgsql support pass: branches on PIWIGO_DB_DRIVER the same way
# IntegrationTestCase::loadFixture()/RegenerateFixtureTest already do —
# tests/Fixtures/piwigo-17.0-pgsql.sql (the real pg_dump sibling, same file
# IntegrationTestCase::pgsqlFixturePath() derives) loaded via `psql -v
# ON_ERROR_STOP=1`, matching that class's own loadFixtureViaPsql() flags
# exactly (a bare psql run here isn't piped through proc_open, so the
# EPIPE-on-unread-stdout gotcha documented there doesn't apply — this
# script lets psql's own preamble SELECT print straight to the terminal).
#
# The galleries_url/categories.lastmodified corrections every fresh
# reimport needs live in tests/Support/FixtureNormalizer.php, run below
# via tools/normalize-fixture.php -- the same shared implementation
# IntegrationTestCase::loadFixture() uses for its own separate,
# non-shell-script import path, so both stay in lockstep. See that
# class's own docblock for why each correction is needed.

set -euo pipefail

set -a
source .env.test
set +a

# This script always runs from the project root (composer.json's own
# `test:browser`/`test:visual` scripts invoke it as `bash tools/reimport-fixture.sh`
# from there) -- $(pwd)/ is this checkout's real Paths::$root value.
real_root="$(pwd)/"

if [ "${PIWIGO_DB_DRIVER:-mysqli}" = "pgsql" ]; then
  psql_args=(-v ON_ERROR_STOP=1 -q -U"${PIWIGO_DB_USER}" -h"${PIWIGO_DB_HOST}" -d"${PIWIGO_DB_BASE}")
  if [ -n "${PIWIGO_DB_PASSWORD:-}" ]; then
    export PGPASSWORD="${PIWIGO_DB_PASSWORD}"
  fi

  psql "${psql_args[@]}" -f tests/Fixtures/piwigo-17.0-pgsql.sql

  until psql "${psql_args[@]}" -c "SELECT COUNT(*) FROM images;" > /dev/null 2>&1; do
    sleep 0.5
  done
else
  mysql_args=(-h"${PIWIGO_DB_HOST}" -u"${PIWIGO_DB_USER}")
  if [ -n "${PIWIGO_DB_PASSWORD:-}" ]; then
    mysql_args+=(-p"${PIWIGO_DB_PASSWORD}")
  fi

  mysql "${mysql_args[@]}" "${PIWIGO_DB_BASE}" < tests/Fixtures/piwigo-17.0.sql

  until mysql "${mysql_args[@]}" "${PIWIGO_DB_BASE}" -e "SELECT COUNT(*) FROM images;" > /dev/null 2>&1; do
    sleep 0.5
  done
fi

php tools/normalize-fixture.php "${real_root}"

sudo rm -rf _data/cache/piwigo.*/
sudo rm -rf _data/combined/*
sudo rm -rf _data/i/*

php tools/regenerate-fixture-photos.php
